### ISSUE TITLE
In case of multiplicities 0..1 or 1..1, should assoc return the object itself?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#105]
Currently, assoc returns a collection regardless of the multiplicity:

```java
Collection<OtherClass> coll = assoc(assocEnd.class);
OtherClass obj = coll.selectAny();
```

However, this could be changed to return the object itself (or null) in case of multiplicities 0..1 and 1..1 (MaybeOne and One):

```java
OtherClass obj = assoc(assocEnd.class);
```

Pros:
 * Simpler, shorter to use.
 * More natural.

Cons:
 * Must use null values in case of 0..1 multiplicities.

Note: it could be a contra that this change needs to be applied to every level of our implementation. However, with #59, association navigations has to be changed nevertheless.

**Comment by kovacsgabor** [comment]
@djnemeth, would this feature make the XtxtUML compiling harder or simpler?

**Comment by djnemeth** [comment]
Technically, the compilation itself wouldn't have to be changed, as currently the navigation expression in XtxtUML is simply [mapped](https://github.com/ELTE-Soft/txtUML/blob/2cd7b763994b63024a0af05a210f415b06e8173a/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/compiler/XtxtUMLCompiler.xtend#L59) to an `assoc` call, which would remain the same. However, type computation would need a little adjustment, but nothing complicated, I believe.

**Comment by kovacsgabor** [comment]
It should be considered, that if this is implemented, the following code may fail with a ```NullPointerException```:
```java
this.assoc(assocEndWithMaybeOneMultiplicity.class).assoc(otherAssocEnd.class)...
```

**Comment by kovacsgabor** [comment]
The other possibility in case of association ends with a multiplicity of 0..1 or 1..1 is to use a special collection which may contain at most one element. Java 8's ```Optional```, for example, but I would suggest defining a different one that would only have three methods: ```assoc```, ```isEmpty``` and ```selectOne``` (or simply ```one```, or ```get```).

**Comment by kovacsgabor** [comment]
The team refused this proposal.
