### ISSUE TITLE
Author tags?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#109]
Do we wish to keep the author tags in JavaDoc? Or to add new in the future? Their use is not consequent at all.

**Comment by nboldi** [comment]
I see no use for them. I think they only encourage personal code-ownership instead of shared ownership.

**Comment by kovacsgabor** [comment]
@ELTE-Soft/all, what is your opinion?

**Comment by kmate** [comment]
I agree with nboldi, I never use them. Also, Git already tracks all changes with author information on a more fine-grained level...

**Comment by gerazo** [comment]
I think the only name(s) which makes sense in a javadoc are the developer(s) to whom I can turn to if I have technical questions. It is more like knowledge ownership instead of the classical one for which we are all responsible. The closest term which comes to my mind is "maintainer(s)".

**Comment by dobreffandras** [comment]
Although I can fully agree with @gerazo  to keep the reliability and consistency we strictly need to stick to some rules. I doubt it can be done with 100% success, and if it's not used precisely can easily cause confusion. This case is the typical "Not doing at all is better than doing it wrong" in my opinion.

**Comment by nboldi** [comment]
It would be better if we would just assign each plugin project to one of the members of the team, instead of littering all the classes with author tags. For example, the model.api plugin should be overviewed by @kovacsgabor, the releng projects by @gerazo, the validator by myself.

**Comment by devaigergely81** [comment]
I think the conclusion is to remove the author tags. Someone who is bored, please take this issue. :-)
