### ISSUE TITLE
Layout export is not exporting states and transitions

### ISSUE THREAD

**Issue by GregoBalu** [ELTE-Soft/txtUML#118]
States and transitions are not exported as nodes and links, so the textual layout visualization of state machines (#4) cannot continue.

There are TODOs marking the missing parts as shown below:

![layout_export_todo](https://cloud.githubusercontent.com/assets/8973441/11015104/6db79e74-8551-11e5-8722-e5b24a352c8d.png)

@djnemeth @kovacsgabor

**Comment by devaigergely81** [comment]
@GregoBalu, if you can implement it, feel free to do so in a branch, and create a pull request.

**Comment by kovacsgabor** [comment]
It is not a big deal for someone who is familiar with those parts of the code, so I will do it.
