### ISSUE TITLE
hu.elte.txtuml.layout.visualizer.helpers

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#120]
Some utility features are implemented in the ```hu.elte.txtuml.layout.visualizer.helpers``` package unnecessarily. I found the following two examples:

 * A ```Pair``` implementation is already used by multiple other txtUML projects, and is defined in ```hu.elte.txtuml.utils```.
 * A ```BiMap``` implementation is present in the ```com.google.common.collect``` package, a part of Guava, which we already have a dependency on.

Also, it should be considered to move some other general-purpose classes of this ```helpers``` package (like ```Triple```, ```Quadraple```) to the ```utils```project to let other txtUML projects use them in the future.

**Comment by kovacsgabor** [comment]
Another minor issue regarding this package: The JavaDoc of ```Quadraple``` is wrong (it is the same as the documentation of ```Triple```).

**Comment by GregoBalu** [comment]
I did everything suggested above except BiMap.

**Comment by kovacsgabor** [comment]
Is there a specific reason you ignored my suggestion about BiMap? If there is, please explain it.

**Comment by kovacsgabor** [comment]
(Unless there is a good reason for it, we agreed that we should not reinvent the wheel. That is why I suggested using the existing BiMap implementation.)
