### ISSUE TITLE
hu.elte.txtuml.project depends on hu.elte.txtuml.diagnostics

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#124]
These two projects should not depend on each other in any way.

The dependency is only present because they use the same methods to log errors. This logging capability should be put to a common utility project.

**Comment by nboldi** [comment]
There should be a mass restructuring of plugins in the project, because there are a lot of unnecessary couplings that cause strange dependencies.

**Comment by nboldi** [comment]
Relevant pull request: #201
