### ISSUE TITLE
State machines as separate classes?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#128]
```java
class SM extends StateMachine<A> {
	
	// ...
	
	class S1 extends State {
		@Override
		public void entry() {
			self.i = 5;
		}
	}
	
	// ...
	
}
```

Where ```A``` is the type of model class this state machine belongs to and ```self``` is a protected final field of ```StateMachine``` which's type is naturally ```A```.

On the other side, ```A``` also has to know about ```SM```. This can be done in various ways, the most obvious two would be to use annotations or to use generics:

```java
@StateMachine(SM.class)
class A extends ModelClass { /* ... */ }

// or

class A extends ModelClass<SM> { /* ... */ }
```

Pros:
 * More separation, smaller files.
 * Can be continued to put also the inside of composite states into separate files.

Cons:
 * More code.
 * Using ```self``` is obligatory.
 * Problem with visibility (```SM``` cannot access the private fields of ```A```).

**Comment by GregoBalu** [comment]
What about:
```java
class SM extends A implements StateMachine{ ... }
```
But I like it. The 'self' is not a big problem as it's still shorter then the current 'A.this'.

**Comment by kovacsgabor** [comment]
```self``` is shorter than ```A.this```, that's true, but ```A.this``` can be omitted in most cases, whereas ```self``` would have to be explicitly written every time.

**Comment by kovacsgabor** [comment]
The majority of the MDD team agreed that moving state machines into separate files is not worth its price.

It can be assumed that the model classes will either contain very big state machines as most of the business logic is implemented inside them, or the opposite, they become relatively small if the action code is written in private operations which are called from transition effects, state entry or exit actions. In either case, one of the two files (the state machine or the class) would be relatively small.

**Comment by kovacsgabor** [comment]
The majority of the MDD team agreed that moving state machines into separate files is not worth its price.

It can be assumed that the model classes will either contain very big state machines as most of the business logic is implemented inside them, or the opposite, they become relatively small if the action code is written in private operations which are called from transition effects, state entry or exit actions. In either case, one of the two files (the state machine or the class) would be relatively small.

**Comment by kovacsgabor** [comment]
Another problem is supporting two syntaxes is not an easy task and can easily lead to issues in the future. Therefore, if we choose to support separate state machines, we may need to make their use mandatory and it can be very inconvenient in case of small classes.

**Comment by kovacsgabor** [comment]
@greti noted that moving the action code into separate files would be far more beneficial as the structure of the state machine presents valuable information about the behavior of the class' instances whereas many lines of action code can be rather annoying to scroll through.

The closest we can currently get to this is using private methods (operations in the model) which then may contain the action code.

**Comment by kovacsgabor** [comment]
To sum up, this proposal is unsupported by the team members.
