### ISSUE TITLE
No CompositeState/composite?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#129]
It is a possibility to remove CompositeStates/composites from the txtUML language and use States/states instead.

In this case, a composite state would be a state that has an initial state defined inside it.

Pros:
 * Less language elements.
 * Less constraints.

Cons:
 * A bit slower runtime (every state has to be checked whether it contains an initial state).

**Comment by kovacsgabor** [comment]
The team agreed to support this.

**Comment by nboldi** [comment]
I would advise against this if there is no serious reason to do that.

**Comment by kovacsgabor** [comment]
Please, explain your reasons to advise against this.

**Comment by nboldi** [comment]
Marked composite states are easier to handle, both at runtime and compilation time (validation). Moreover by looking at a type declaration, it should be clear if it is a composite state or a simple one, like it should be clear if a type declaration stands for a class or a simple data type.

**Comment by kovacsgabor** [comment]
I take back this proposal.
