### ISSUE TITLE
Layout language in an imperative way?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#130]
Current syntax:

```java
class D extends Diagram {
  @North(val = A.class, from = B.class)
  class L extends Layout {}
}
```

Proposed syntax:

```java
class D extends Diagram {
  @Override
  public void layout() {
    north(A.class, B.class);
  }
}
```

**Comment by GregoBalu** [comment]
Look-wise I like the second (proposed) syntax, but we would lose those identifiers (val, from, bottom, top, end, ...) which are helpful in certain situations.

**Comment by kovacsgabor** [comment]
Also, the so-called anonymous groups, like
```java
@North(val = {A.class, B.class, C.class}, from = D.class)
```
would have to become more explicit. With either arrays
```java
north(new Class<?> { A.class, B.class, C.class }, D.class);
```
or some kind of static methods, returning arrays or collections, like
```java
north(Arrays.asList(A.class, B.class, C.cass), D.class);
```

**Comment by kovacsgabor** [comment]
Ideas on the issue from the weekly meeting:
 * Lot more validation is needed in the modified version.
 * Others agreed with @GregoBalu that the missing parameter identifiers may reduce readability.
