### ISSUE TITLE
The runtime API lacks proper error handling

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#131]
The current implementation of the runtime API is based on the following rules:
 * If the model is invalid, nothing is guaranteed.
 * After reporting an error, nothing is guaranteed.

By "nothing is guaranteed", I mean that in these cases the API may throw surprising or uninformative exceptions (typically NullPointerExceptions) or result in an unspecified behavior.

The team agreed that a better error handling is required.

**Comment by nboldi** [comment]
My proposal:
 - The runtime can assume a valid model and should not manually check model validation. If it is clear that the model is invalid, it should exit with a general error message. (Validation is improving.)
 - If the user performs an operation that is illegal in the current state, the runtime should roll back the changes and the execution should continue as if nothing happened. If it is not possible (for example: the operation had some return value that could be used later), it should stop after giving the error message to the user.
