### ISSUE TITLE
The project needs a general logging infrastructure

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#132]
Currently, the different parts of txtUML uses different approaches to logging and error handling. In my opinion, the whole project should use a general solution.

**Comment by gerazo** [comment]
Our expectations from logging are the following:
1. Can log to the PDE log on the Eclipse side
2. Can use simple logging on the runtime side
3. Logs can be tested for in unit tests

**Comment by gerazo** [comment]
Log4j is quite widespread (and according to @djnemeth) is already used in our project (by 3rd part stuff, xtext), so why not put that into action?

**Comment by nboldi** [comment]
This should be solved along with #124.

**Comment by nboldi** [comment]
The model should use a different logging than the eclipse integration parts, because it should work without eclipse integration.

**Comment by gerazo** [comment]
Yes. It can be log4j as well but configured differently on the model side.

**Comment by kovacsgabor** [comment]
As I see, it is solved by #201.
