### ISSUE TITLE
A test of api.model fails

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#133]
The test about calling Action.create with wrong parameters fail with IllegalArgumentException.

**Comment by gerazo** [comment]
These tests were disabled in maven, see https://github.com/ELTE-Soft/txtUML/commit/6b896f0f59e00500a4a0521f13eb7d1d7bc2eff2
If you are ready with the fix, do not forget to remove the pom.xml changes to put the tests back alive.
