### ISSUE TITLE
Composition association

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#138]
Initial syntax proposal:
~~~~
// JtxtUML:
class MyComposition extends Composition {
  class MyContainer extends Container<A> {}
  class MyPart extends Many<B> {}
}
~~~~
~~~~
// XtxtUML:
composition MyComposition {
  container A MyContainer;
  0..* B MyPart;
}
~~~~

**Comment by kovacsgabor** [comment]
The container is always a navigable association end with 1..1 multiplicity?

**Comment by devaigergely81** [comment]
The UML standard says it is 0..1.

**Comment by nboldi** [comment]
@kovacsgabor, @devaigergely81, all associations are nested directly in the model? Is this true after splitting models into separate files?

**Comment by kovacsgabor** [comment]
After splitting models into separate files, associations become top level classes.

I'd also consider changing them to be interfaces for simpler use but either way, they will **not** be nested classes.

**Comment by kmate** [comment]
I suggest to implement it in XtxtUML only after branch split-models is merged back, as it contains radical modifications on JVM model inference.

**Comment by nboldi** [comment]
I consider the JTxtUML part finished.

**Comment by kmate** [comment]
The XtxtUML part is also completed. I added several validation rules for associations in class `hu.elte.txtuml.xtxtuml.validation.XtxtUMLAssociationValidator`. These can be useful in JtxtUML too.

**Comment by nboldi** [comment]
We shuold talk about development of the validation plugin. There are a lot of improvements that can be done.

**Comment by nboldi** [comment]
Runtime check needed: two composite association cannot be active for an object.

**Comment by nboldi** [comment]
Runtime check is implemented. Can be merged after split-branch is completed.

**Comment by kovacsgabor** [comment]
Do we need a hidden (non-navigable) version of the container end?
