### ISSUE TITLE
Remove the parameter of getSignal?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#139]
The ```getSignal``` method is used inside the actions of transitions and states to get the signal instance which triggered the actually performed transition. It performs an unchecked cast to any desired type that extends Signal as we are unable to ensure the safety of this cast at compile time.

Currently, this ```getSignal``` method has one parameter, the ```java.lang.Class<?>``` object of the signal type that the user wishes to cast to. So it is used like:

```java
MySignal sig = getSignal(MySignal.class);
```

Originally, ```getSignal``` had no parameter (just a type parameter, which does not need to be explicitly written in the code) as this cast can be performed without that ```Class<?>``` object. The parameter was introduced because it was a necessity for the reflection-based model exportation.

As we now export the models with JDT, this parameter could be removed again to provide the following syntax:
```java
MySignal sig = getSignal();
```

**Comment by devaigergely81** [comment]
Agree.

**Comment by kovacsgabor** [comment]
The team agreed to support this proposal.
