### ISSUE TITLE
Port-based communication in txtUML

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#145]
Current txtUML supports signal sending directly to objects. In addition to this, UML supports port-based communication as well, which is needed for component-based architecture modeling. This proposal is about adding elements to txtUML to make port based communication possible.

A class can have ports. These ports are typed by provided and required interfaces. The proposal is to limit these interfaces to contain signals only. The signals of the provided interface can arrive to the port, while signals of the required interface can come from the port.

In order to define communication channels between ports, we need the notion of *parts*. Parts are defined by the composite associations: If there is a composition between classes A and B such that A is the owner and the role name at B is b, then b is a part of A. Parts can be visualized on UML composite structure diagrams. Note that if there are two different compositions between A and B, A will have two different parts, both of type B. When a class instance is deleted, it must delete its parts as well. Any instance can be owned by at most one instance at a time.

Ports can be behavior ports, meaning that all signals arriving to that port will be transferred to the state machine of the class for processing. Other ports of a class can be connected to ports of the parts of the class, by so called *delegation connectors*. A port of a part of a class can be connected to a port of a part of the same class by a so called *assembly connector*. The interfaces at the two ends of a delegation must be the same. The interfaces at the ends of an assembly must be *conjugated*, that is, the provided interface at one end is the required at the other end and vice versa.

Ports can have multiplicities, it is a TODO to elaborate the details of that.

This proposal is about adding the above mentioned elements to txtUML with the possibility to combine them in any way. Therefore it would be possible to send signals to an instance directly and through its ports, call its operations, access its attributes and the class could have any kind of composite and non-composite associations in the model. Of course, using all these features together will limit how the instances could be deployed in different threads, processes and machines in run-time. Therefore, having different deployment scenarios will imply constraints on the model. In order to elaborate these constraints in full detail, we first need to think about how to describe the deployment and what scenarios will be allowed there.

Anyway, as an example, here are a set of constraints necessary to be able to place an instance of a class into a separate process:
  * The class communicates only via ports, this communication is restricted to asynchronous signals, and signals hold primitive data (and data types built from primitives) only.
  * The class has no associations, except composite associations that define its internal structure.
  * The class has no public operations except constructors.
  * The class has no static attributes.
  * There is no *select any* and *select all* operations used on this class. (If this would ever be supported in txtUML.)

**Comment by gbatori1** [comment]
The term ConnectorEnd multiplicity is missing which is needed when multiple objects want to communicate out from the class which owns them. This might be a next iteration but it should be taken into consideration when the runtime is defined.

**Comment by kovacsgabor** [comment]
JtxtUML syntax proposal (based on the version of txtUML which supports capsules):

For ports:
(Prov is the provided, Req is the required interface)
```java
class C extends ModelClass {
	class P extends Port<Prov, Req> {}
	// ...
}
```
For interfaces:
(S1 and S2 are signals)
```java
interface Prov extends PortInterface {
	S1 s1();
	S2 s2(String str, int i); // S2 has a (String, int) constructor
}
```
or:
```java
interface Prov extends PortInterface {
	void s1(S1 sig);
	void s2(S2 sig);
}
```

Sending signals:
```java
//inside the action code of a model class
// port() returns the provided interface of a port instance
port(P.class).s1();
port(P.class).s2("test", 10);
```
or

```java
port(P.class).s1(new S1());
port(P.class).s2(new S2("test", 10));
```

If ports have multiplicities, port() can have an int parameter as the index of the required port or anything else that we wish to identify the ports with.

Of course, this way the interfaces must be instantiated through reflection (proxies) to send (or, in the first version, even instantiate) the specified signals to the actual port.

**Comment by nboldi** [comment]
So there will be no concept of a component, just a restricted class?
Additional rule:
 - Between these classes, a composite association cannot return a reference (must send a signal when using the composition).

**Comment by devaigergely81** [comment]
In the first round there will be no restrictions at all. We just add interfaces, ports and connectors to normal classes. (Like in the UML standard.) Then we have to do experiments how is it best used in parctice. Based on the experiences, we might define restrictions. I know about two possible ways to introduce restrictions:
- Marking different classes as "components", which will enforce restrictions to make the component a black box. When deployment descriptions are added to the project (additional input to the code generator, describing how to map the software to processes and threads), these descriptions are checked if they can be realized by the model.
- An even better way would be to add different deployment scenarios to the project in parallel to creating the model itself, and then the model is checked if it can fulfill the requirements of all scenarios.

**Comment by devaigergely81** [comment]
Most of it is resolved and the remaining part is factored out in #289, so I close this.
