### ISSUE TITLE
Poor XtxtUML error message for class outside the model

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#15]
Change the 'model' keyword to 'class'. A strange error message is generated.
![class_outside_model](https://cloud.githubusercontent.com/assets/7555116/10482019/17d29d7c-7275-11e5-9cde-8c844f94e964.png)

**Comment by kmate** [comment]
This is also a problem with misplaced states and so on... I suggest to follow the recommended way of solving this in Xtext: use a loose grammar and strict validation. So we should create a grammar, where each of these structured elements are allowed at every level to the root, and validate their structural correctness.

**Comment by kovacsgabor** [comment]
I think the originally reported problem is outdated now with the classes not being inside a model code block anymore. Is this issue still relevant because of the other cases mentioned by Máté?

**Comment by devaigergely81** [comment]
I do not think this is valid any more.
