### ISSUE TITLE
hu.elte.txtuml.export.uml2.tests fail under Maven

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#151]
hu.elte.txtuml.export.uml2.tests fail under Maven. The project's pom.xml was modified to skip these tests in maven until they are fixed, see: https://github.com/ELTE-Soft/txtUML/commit/6b896f0f59e00500a4a0521f13eb7d1d7bc2eff2
You can run the tests in the parent project dir using "mvn verify"
If you fixed the issue, do not forget to restore the pom.xml to enable the tests in the test system again.

**Comment by kovacsgabor** [comment]
Is this fixed now, @nboldi?

**Comment by nboldi** [comment]
Yes, uml2 export tests are running

**Comment by gerazo** [comment]
:+1:
