### ISSUE TITLE
Correct line endings

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#161]
Step 1. Set git repo specific line-ending settings
Step 2. Get rid of those Windows line endings once and for all

**Comment by kovacsgabor** [comment]
I think this should be done along with other planned or proposed global code changes, like #109.

**Comment by gerazo** [comment]
Solved: https://github.com/ELTE-Soft/txtUML/commit/71fa6ef7d9a4f0271f6c2f4731174b3fd868e68a
