### ISSUE TITLE
hu.elte.txtuml.layout.export.tests fail

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#164]
The tests of the layout.export project have to become plug-in tests.

**Comment by gerazo** [comment]
This was the error message: [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.24.0:validate-version (default-validate-version) on project hu.elte.txtuml.layout.export.tests: Unqualified OSGi version 0.2.0.qualifier must match unqualified Maven version 0.3.0-SNAPSHOT for SNAPSHOT builds

**Comment by gerazo** [comment]
This means you've set the wrong version number in the child project of maven. We have stepped up to version 0.3.0 and your project was still 0.2.0. Apart from this the project was correctly set as a plugin test.

**Comment by gerazo** [comment]
Unfortunately, master is broken so I've put a hotfix on that directly. (Otherwise everyone will merge a broken version into their work)

**Comment by gerazo** [comment]
Fixed in: https://github.com/ELTE-Soft/txtUML/commit/498bb8743429cf420cf96bff7da6e64518f9b6ae

**Comment by kovacsgabor** [comment]
Sorry for that. Thank you for fixing it!
