### ISSUE TITLE
Rename getSignal as sigdata?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#166]
In XtxtUML, the triggering signal instance can be get with the sigdata keyword in transition effects and state entry/exit actions. In JtxtUML, the same can be achieved with the getSignal method of the Transition and State API classes.

The proposal is about to rename the getSignal method of JtxtUML as sigdata to get the two syntaxes closer to each other.

**Comment by kovacsgabor** [comment]
What do you think, @ELTE-Soft/all?

**Comment by gerazo** [comment]
I generally like the idea. I like even if it is not like Java conventions... on the other hand it is similar to CPP getters. But will it be consistent with other things in the system? Like for ports and assocs using get seems to follow a different convention.

**Comment by kovacsgabor** [comment]
My primary aim was to bring the two syntaxes closer. I think that it is problematic if the two has different names for the same thing. It is also a solution if we rename the X version, though.

**Comment by gerazo** [comment]
I agree

**Comment by devaigergely81** [comment]
If this function returns a signal, I prefer `getSignal` both in X and J.

**Comment by kmate** [comment]
I agree with @devaigergely81, but it seems a little bit weird to have `getSignal()` in X. If it is a method call, what is the `this` object of it? Doesn't it complicate the implementation? If it is a keyword, as currently, I would prefer simply `signal` instead of `sigdata` or `getSignal`.

**Comment by kovacsgabor** [comment]
Currently, it is a keyword in X, which makes `getSignal` strange for me as well.

Note: As far as I know, `sigdata` comes from rALF. Is it true, @djnemeth?

**Comment by djnemeth** [comment]
@kmate, you're right, it would be problematic to make the `getSignal` method available in XtxtUML, as we changed the binding of `this` in 66e82d2.

@kovacsgabor, yes, it's from rAlf. See #140.

I agree with Máté's `signal` keyword proposal.

**Comment by kovacsgabor** [comment]
It seems that the following proposal is the most supported:
* `getSignal` _method_ in J,
* `signal` _keyword_ in X.
