### ISSUE TITLE
New model wizard has to check if the selected package is already a model

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#175]
Branch: split-model-wizards

Steps to reproduce:
1. create a new txtUML project
2. create a new JtxtUML model in package p
3. create a new XtxtUML model in package p
4. The wizard allows this, and generates the package-info.java in step 2, then generated model-info.xtxtuml in step 3, which causes an error.

If, in step 3, a new JtxtUML model is created again, the wizard shows an error message about the already existing package-info.java. This is correct, however, it could also be improved by already showing (a more user-friendly) error message at the top of the wizard dialog as soon as the package field contains the package of an already existing model, and disabling the Finish button.

**Comment by nboldi** [comment]
I assume that it should also deny creating a model as a subpackage of an existing model.

**Comment by kovacsgabor** [comment]
Yes, it should.

**Comment by nboldi** [comment]
Solved it. Please, review.

**Comment by devaigergely81** [comment]
OK.
