### ISSUE TITLE
XtxtUML as default language in 'New model' wizard

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#184]

**Comment by devaigergely81** [comment]
I agree with this suggestion originally proposed by @kovacsgabor in #171. What do @ELTE-Soft/all think?

**Comment by nboldi** [comment]
I think it is a management question. Which technology is the primary product? Is XtxtUML just a nice syntactic sugar? Is JtxtUML a replacement if something goes wrong with the toolchain?

**Comment by dobreffandras** [comment]
I have the same question as @nboldi "Which technology is the primary product?"
Do we want to set default the one which is more convenient to the user (X) ?
(As I see once the user had tried out the DSL, won't write models in the J syntax)
Or do we want to emphasize that our product is a modelling tool in Java with an optional syntax?

**Comment by devaigergely81** [comment]
In an Eclipse wizard the X syntax is a safe default option. The Java variant is important outside Eclipse: I know about an upcoming project where someone wants to *generate* txtUML models and run them automatically (headless Eclipse or without Eclipse) for simulation purposes. In this case the J syntax seems to be a better technical solution.

**Comment by gerazo** [comment]
Unfortunately, without measuring on a broad enough, independent user-base, we cannot surely tell if X or J is better. Our opinion as developers does not count, only real use-cases, user interviews.

**Comment by kovacsgabor** [comment]
The team decided to support this proposal for now.
