### ISSUE TITLE
Unversion Xtext-generated code

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#186]
Originally, we decided to put the generated code of Xtext under version control to make the development environment simpler. Now that we have Maven-based releng in place: Is it possible to do the 'Generate Language Infrastructure' step automatically, so that we could un-version the generated files? If that cannot be part of the build, we might still consider un-versioning and adding one more manual step to the setup of the development environment. What do you think, @ELTE-Soft/all?

**Comment by gerazo** [comment]
We should unversion them at all costs. Even if it needs extra setup steps. I will look into it.

**Comment by gerazo** [comment]
Done
