### ISSUE TITLE
New txtUML Model wizard should set a default value for source directory

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#19]

**Comment by dobreffandras** [comment]
Please sepcify in which use cases is it necessary to provide a default value.
If the user opens the model creation wizard without selecting a project, a default value for source directory cannot be added. Thus the following use cases are reasonable:
 - The user right-clicks on a project
 - The user right-clicks on a source folder
 - The user right-clicks on a package

**Comment by kovacsgabor** [comment]
Currently, if the user right-clicks on a source folder or package (or chooses File->New->... when a source folder or package is selected), the appropriate source folder is set as default value. It could be further improved to propose a source folder even if only a project is selected but as the user is able to quickly browse for a source folder in this case, I think it isn't worth the effort.

**Comment by kovacsgabor** [comment]
Could this issue be closed?

**Comment by dobreffandras** [comment]
Not yet. It's a minor issue and I always had others to do.

**Comment by kovacsgabor** [comment]
Yes, it does. I don't know who implemented it, but it works.

**Comment by dobreffandras** [comment]
Oh, sorry I did not see your previous comment. 
If the current status is acceptable as a user, then yes this Issue can be closed.
