### ISSUE TITLE
Support for ports and connectors in XtxtUML

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#190]
Dependent on #189.

**Comment by kovacsgabor** [comment]
Syntax proposal for interfaces:
```
interface {
  reception Sig1, Sig2, Sig3;
  reception Sig4;
}
```

**Comment by kovacsgabor** [comment]
Syntax proposal for ports:
```
  // inside a class
  [internal] [behavior] port myPort {
    required Ifc1;
    provided Ifc2;
    // in the future:
    [multiplicity 1;] // if omitted, then multiplicity is 1
  }
```

**Comment by kovacsgabor** [comment]
Syntax proposal for connectors:

```
connector myConn {
  1 myPort@myRole myName;
  myPort2@myRole2 myName2; // 1 is optional
}
```

**Comment by kovacsgabor** [comment]
Syntax proposal for send command:

```
send new MySignal() to portInstance;
```

Syntax proposals to query port instances:
1)
```
myport@obj

myport // @this is optional
```
2)
```
this->myport
```

**Comment by devaigergely81** [comment]
It is also an option to use `->` in connector definitions:
```
connector myConn {
  1 myRole->myPort myName;
  myRole2->myPort2 myName2; // 1 is optional
}
```
and the same symbol for port access (as in the previous comment):
```
this->myport
myport // this-> is optional
```
- Pro:
  - The arrow symbol would mean: *accessing a special property*. This holds both for ports and association ends: these are properties according to the UML standard.
  - No need to introduce a new symbol (`@`), which is not familiar to programmers of mainstream object oriented languages.
- Con:
  - `myPort@myRole` could be read in a more natural way.

**Comment by djnemeth** [comment]
I agree with @devaigergely81 regarding the `->` syntax variant. @kovacsgabor, can you think of any possible drawbacks apart from the one mentioned in the previous comment?

**Comment by kovacsgabor** [comment]
No, I cannot.

**Comment by kovacsgabor** [comment]
The team supported the `->` syntax if it is achievable.

**Comment by kovacsgabor** [comment]
In case of the connect operation, the API `Action.connect` methods will be called in XtxtUML as well.
