### ISSUE TITLE
Support for data types in JtxtUML

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#191]
Data types are restricted versions of classes: cannot have state machine, it is not possible to start their behavior, cannot accept messages etc.
In contrast to normal classes, data types can be used as attribute types in signals, classes and also in other data types.
They are passed and sent always as values, using copying semantics. Instances have no "identity".

We have to think (and read the UML standard) about associations, compositions for data types. Alternatively, we could introduce attribute multiplicities.

**Comment by nboldi** [comment]
Decisions:
 - Data types cannot have associations.
 - Fields of datatypes must be other datatypes, enums, or primitive types.
 - All fields of datatypes must be final.
The first implementation has no multiplicities on fields.

**Comment by nboldi** [comment]
Data type support is also implemented in #200. Sorry for putting solutions for two different issues in one pull request, but it saves a lot of bookkeeping.

**Comment by kovacsgabor** [comment]
Isn't this completed yet?

**Comment by kovacsgabor** [comment]
The base class DataType has already been created in the modeling API.

The only question is, whether we would like to add any support for data types in J apart from validation rules (like data types may only have final fields)? Possible features include equals and hashCode methods in the base that use reflection (if data types are compulsorily immutable, which I strongly suggest, clone is not required).

@ELTE-Soft/all, opinions?
