### ISSUE TITLE
Support for data types in XtxtUML

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#192]
Based on #191.

**Comment by mykeesg** [comment]
Going through the pull-requests and issues found in the comments, isn't this already completed in #485? That is already merged to the master branch and it says it resolves issue #191, which this issue is based on (but no additional info is here).

**Comment by djnemeth** [comment]
#191 and #485 covered the J part, this issue is about the X part.

**Comment by djnemeth** [comment]
The team have decided to postpone this.

**Comment by berpeti** [comment]
Tasks for implementation:

- [ ] Write grammar rules
- [ ] Complete the inferrer regarding the data types
- [ ] Write validation rules for data types
- [ ] Write auto formatting, import organizer rules for data types
- [ ] Write the tests (compiler tests, validator tests, etc.) for data types
- [ ] Extend the example projects with the X-style data types
