### ISSUE TITLE
Get rid of Moka

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#193]
Reasons:
- Moka is a Papyrus-based UML execution framework mainly for execution and debugging of activities. We only use a utility class of it in order to animate state machines.
- There is a known issue with Moka: If the model grows huge or references huge models, Moka freezes the application when it searches for all possible diagrams that the given model element might appear on. Since we animate state machine diagrams generated by us, we know exactly which elements are on which diagrams, so we can avoid this performance bug of Moka.
- Later we plan to show the animation of more than one instances of the same class on a single state machine diagram by color coding. In order to enable this, we have to directly control the colors of the animation instead of the Moka defaults.

How:
- Find out the Papyrus API to change the fill/border color or model elements. (Possibly by reviewing the implementation of Moka).
- Change the state machine animation implementation to use that API directly.
- Remove Moka from the dependencies.

**Comment by gerazo** [comment]
I like it

**Comment by gerazo** [comment]
Reminder: As soon as PR203 is in, the wiki needs to be corrected to reflect that Moka installation is no longer needed

**Comment by gerazo** [comment]
And finally shit hit the fan: the proposed solution (getting-rid-of-moka branch) on a freshly installed Eclipse where Moka was never installed. The reason that putting markers on objects is not enough to have animation. Moka probably uses some extension points to inject new functionality into the rendering of objects, but what is sure that it uses CSS stylesheets to parameterize the outlook of the animation. When Moka is not installed, these parts are missing and nothing is seen.
However there are examples how to directly modify the rendering of an object through Papyrus EditorParts.

**Comment by gerazo** [comment]
Issue was fixed in linked PR.
