### ISSUE TITLE
Validation improvements

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#195]
See: https://github.com/ELTE-Soft/txtUML/tree/validation-improvements

**Comment by nboldi** [comment]
Refactoring and completing structural validation. Adding unit tests for validation.

**Comment by devaigergely81** [comment]
If not yet done in this branch, please fix the validation so that the Timer type from the txtUML standard library is allowed as type of attributes.

**Comment by nboldi** [comment]
Relevant pull request: #200

**Comment by nboldi** [comment]
I implemented that interfaces extending ExternalType are valid field an parameter types.
