### ISSUE TITLE
Re-export of unchanged model

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#2]
Diagram generation re-exports the UML model each time a diagram is generated. Re-export should only be done if the txtUML model has changed. Otherwise only the changed diagrams should be re-generated.
(The long-term goal is incremental transformation.)

**Comment by nboldi** [comment]
I close this issue, because I don't think it is still relevant now. Currently the development is not going toward incremental transformation, and exporting the layout is not much bigger with the structural parts of the UML model exported.
