### ISSUE TITLE
Navigation expressions should use dotted qualified names

### ISSUE THREAD

**Issue by kmate** [ELTE-Soft/txtUML#204]
Currently the navigation expression specifies association names with double colons (::). They should be specified by ordinary qualified names, which are separated by dots (.). This change enables simplifications in qualified name handling.

However, the implementation of this feature is not quiet straightforward, as the navigation expression should be converted into an abstract feature call in the grammar. The following snippet shows an example how to do this:

~~~~
XMemberFeatureCall returns xbase::XExpression :
	XPrimaryExpression
	(
...
	| 
		=>({RAlfAssocNavExpression.target=current} '->') feature=[types::JvmIdentifiableElement|ValidID]
	)*
;
~~~~

This solution results in a conflict-free grammar, but the type computations needed are not trivial, as it also involves scoping and linking services. I consider this as a relatively hard task, so we should decide whether to implement this in the future.

**Comment by djnemeth** [comment]
In the rAlf specification I've seen some months ago, `::` was used in qualified names instead of `.`. Have the proposed syntax changed since then?

**Comment by kmate** [comment]
As far as I know we don't have to follow the rAlf specification anymore. Using only dots for delimiting names would make the language more consistent.

**Comment by kovacsgabor** [comment]
The team agreed on the following:

```.``` will be used both in qualified names and for feature calls. However, the qualified name after the ```->``` will be put in brackets.

Some examples:
```java
this->(AB.a);
this->(AB.a)->(AC.c);
this->(AB.a).one();
```
