### ISSUE TITLE
Sequence diagram syntax proposition

### ISSUE THREAD

**Issue by zoltanturi89** [ELTE-Soft/txtUML#208]
The priority in the construction of this syntax was to be as similar as possible to the existing structures ( Statechart diagram and Class diagram api).
This is a first "draft" version, so it will be refined in the following days/weeks.

Defining a diagram looks like this in this version:

``` java
    public class version1 extends SequenceDiagram {
          //Diagram content goes here
    }
```

Defining an instance of an object is simple extending of an existing ModelClass:

``` java
    class TestInstance extends ModelClass{}
```

Actors should be plain Java objects annotated by the Actor annotation( there is a way to skip this element,, which will be further described when discussing sending messages) or can be model Classes annotated in such way.
The first message must be sent from an Actor for the diagram to be valid.

Sending messages:

``` java
    @From(User.class) 
    @To(TestInstance.class)
    @Function(name="test",returnTime=9)  //9 units return time
    class TestMessage extends SendMessage
    {
        /**
         * Returning List of parameters
         */
        @Override
        public List<Object> parameters() {
            //return a list of parameter Objects
        }
    }
```

The syntax is similar to the Class diagram's syntax for associations.
The main concerns with this structure are the Function annotation and the handling of the function parameters.( It is possible to use a Method object here, but acquiring this object is complicated, or we can create a call method with the called object received as parameter to solve the problem.) .
The return time should be calculated in fixed units, and should define the active time after the call. 
In the case we dont want marked Actor classes the from can be ommitted( in this case, the first sender will be named Actor implicitly)

Return messages:

``` java
    @Return(TestMessage.class) //return of which message
    @ReturnObject(Boolean.class) // return class
    class OK extends ReturnMessage
    {

    }
```

Other parameters are unnecessary because we can derive them from the other message received from the annotation. The return object is pretty self-explanatory in this case

The remaining three structures are alternatives,optional, and loop.
The optional structure can be seen as a special alternative, which has no else case so it is ommitted from the examples
So the alternatives look like this:

``` java
    @thenCase(diagram1.class) //Using SequenceDiagrams in the
    @elseCase(diagram2.class) // Optional - no else case means option tag 
    class Started extends Alternative
    {

        @Override
        /**
         * Depends on the currently active object on entering the then diagram or the else diagram
         */
        public boolean Condition(ModelClass obj)  // Current Object received in parameter - a ModelClass so we can calculate the condition.
        {
            //Method stub
        }
    }
```

This definition means that alternative cases must be defined in separate diagrams( and separate files).

Finally, the loop construction:

``` java
    @LoopDiagram(diagram.class) //Define the diagram to run if the condition is true
    class LoopExample extends Loop
    {
        @Override
        public boolean Condition(ModelClass obj) {
            // method stub
        }
    }
```

Both structures require a condition to function. Both conditions depend on the current active class at the point of reaching the block.

**Comment by kovacsgabor** [comment]
On our regular Monday meeting, we agreed to follow a different approach (as long as that proves to be achievable):

The sequence diagrams could be written as action code in some annotated static methods inside the model. This action code might contain special method calls (on an API class like ```Action```) to write not only the communication between the actor and objects of the model but also between objects (and their answers to the actor).

A model execution might be run with such a sequence diagram method as its main method. In this case, the above mentioned special method calls (which represent the communication between objects) would be treated as constraints on on the execution and would be validated. The signals of the model could be annotated as technical signals which would be ignored during this validation.

**Comment by kovacsgabor** [comment]
What is the status of this issue? Is this proposition implemented? Or under development?

**Comment by zoltanturi89** [comment]
I'll start implementing the base, already decided parts( lifelines, basic commands like message sending etc.)
I was waiting for the rework of the ModelExecutor to be finished so i can build on it and adapt a similar coding pattern.

**Comment by djnemeth** [comment]
I believe we can close this now, see #433.
