### ISSUE TITLE
Possibility to declare multiple states in one line when they have no body

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#21]
Instead of:
```
state A1;
state A2;
state A3;
state A4;
```

it would be nice to write

```
state A1, A2, A3, A4;
```

**Comment by devaigergely81** [comment]
Sates usually have some entry and/or exit behaviors inside, in which case the suggestion is not applicable. For states without content, the suggestion is still valid, so I keep the issue with low prio.

**Comment by nboldi** [comment]
I close this issue, because it is not very important, it was just a suggestion.
