### ISSUE TITLE
Empty interface

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#210]
It would be handy to define an `Empty` interface in the modeling API, to be used as generic argument in one-way port definitions.

**Comment by kovacsgabor** [comment]
Can we name it simply ```Empty```? Wouldn't it be better to name it ```EmptyInterface``` or create it as a nested interface of ```Interface``` to be ```Interface.Empty```? My worry is that we use a too general name which we might use in other cases in the language later.

**Comment by devaigergely81** [comment]
`Empty` is already used for the empty containers, I think. I perfer `Interface.Empty`.
