### ISSUE TITLE
Change the order of the parameters of a connector end?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#216]
Currently, in JtxtUML, the first parameter of a connector end is the role, the second one is the port the end connects to.

However, in the proposed XtxtUML syntax, the order is the opposite, which might be a more logical approach as the port is (in most cases) the more important identifier of type of the connector end. Also, the two syntax should be kept as close to each other as possible.

**Comment by devaigergely81** [comment]
If we accept the `role->port` proposal ([see here](https://github.com/ELTE-Soft/txtUML/issues/190#issuecomment-175831271)), then the order would the same as in current JtxtUML.
