### ISSUE TITLE
Rename model keyword in XtxtUML?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#217]
Currently, the keyword ```model``` is used in ```model-info.xtxtuml``` to set the name of the model. This way, however, the word ```model``` has to be written as ```^model``` in any XtxtUML source which is not a problem in itself but as the qualified name of the JtxtUML API packages contain this word, all imports that reference the API appear as ```import hu.elte.txtuml.api.^model.``` which is not really nice.

**Comment by devaigergely81** [comment]
Another solution is to always use `package-info.java` withut XtxtUML alternative.
- Pro:
  - `model` would not be a keyword and the problem of this issue would be solved.
  - Now it is strange that the *new model wizard* makes the user choose between *J* and *X* syntactic variants, but this selection has no consequences later on: It is possible to use both syntaxes, even mixed, independently of the selection in the wizard.
- Con:
  - This would break the current symmetry, that all files can be written in either *J* or *X*.
