### ISSUE TITLE
Remove pingpong example

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#219]
The ```pingpong``` example is very messy. As soon as we have a better one which uses all the port and connector features included in this one, ```pingpong``` should be removed.

**Comment by kovacsgabor** [comment]
@devaigergely81, what do you think about this proposal?

I find the `clock` example a lot better one that could replace `pingpong`, although it does not contain any delegation connectors.

**Comment by devaigergely81** [comment]
We could extend the clock example with delegation connectors:
- The `clock` class could have a port that accept signals to reset the hour, minute and second values. So delegation connectors would go to the three roles.
- Another port could be connected to the `display` to send the time strings out.

**Comment by kovacsgabor** [comment]
After the refactoring in #326, the removal of this example is unnecessary.
