### ISSUE TITLE
Incomplete type usage collection in XtxtUML

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#226]
Although the linking itself occurs on a much higher abstraction level, Xtext provides a [way](https://eclipse.org/Xtext/documentation/301_grammarlanguage.html#syntax) to define cross-references to language elements within the grammar. For example, consider the following parser rule from the XtxtUML grammar: 

```
TUTransitionTrigger :
	'trigger' trigger=[TUSignal|QualifiedName] ';'
;
```

Here, the `trigger=[TUSignal|QualifiedName]` part is an example of the aforementioned grammar-level cross-reference syntax, indicating that the trigger of a transition is an EClass instance of type TUSignal, which EMF type is inferred from the parser rule having the same name.

We use this feature throughout the XtxtUML grammar, as it provides out-of-the-box type validation and content assist support. It also potentially makes some aspects of the runtime faster, as using the `JvmTypeReference` parser rule as an alternative would introduce an additional wrapping layer to be built and maintained for each language-level cross-reference.

<hr>

In the current implementation, however, in an XtxtUML source file, if an _imported_ type is only referenced in abovementioned, grammar-level cross-references, a false warning is issued on the import stating that the type is never referenced.

One can easily reproduce the warning, for example in the following way. Given an XtxtUML model `M` with a class `A`, create a new .xtxtuml file with the following contents:

```
package m;

import m.A;

class B extends A;
```

Here, a warning is shown on the import with the message _"The import 'm.A' is never used."_. Naturally, if the import is removed, the `m.A` class can't be referenced using its simple name, causing an error marker to appear with the message _"Couldn't resolve reference to TUClass 'A'."_.

<hr>

This is caused by the fact that `TypeUsageCollector` – the class responsible for collecting the used types in an Xbase resource – ignores such references, as it can be seen in its [`collectAllReferences`](https://github.com/eclipse/xtext/blob/003a5602d3ddb86fd2204e4e6276e5b109ccdd89/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java#L175) method. I can think of 3 possible solutions:

1. Overriding the aforementioned `collectAllReferences` method to include grammar-level cross-references. I consider this solution quite inelegant, as it would involve direct code copying of the original method (assuming we wouldn't want to iterate through the contents of the resource once again) and other, private auxiliary functions defined in the original class.

2. Intervention in the type usage collection in some other way, for example by extending (but not modifying) the functionality of the overridden `collectAllReferences` method by iterating through the contents of the given resource again. This is a cleaner, but definitely less efficient solution than the first one.

3. Replacing the grammar-level cross-references with `JvmTypeReference`s in the grammar. In this way we would lose the out-of-the-box type validation and content assist support, making the manual implementation of these features necessary. The type computation of some expressions would have to be modified as well. The involved expressions are the following: [`TUClass`](https://github.com/ELTE-Soft/txtUML/blob/e3a8663663e5af26d0430de49bfec5ad943fc130/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L39), [`TUTransitionTrigger`](https://github.com/ELTE-Soft/txtUML/blob/e3a8663663e5af26d0430de49bfec5ad943fc130/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L114), [`TUTransitionVertex`](https://github.com/ELTE-Soft/txtUML/blob/e3a8663663e5af26d0430de49bfec5ad943fc130/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L118), [`TUAssociationEnd`](https://github.com/ELTE-Soft/txtUML/blob/e3a8663663e5af26d0430de49bfec5ad943fc130/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L132), [`RAlfAssocNavExpression`](https://github.com/ELTE-Soft/txtUML/blob/e3a8663663e5af26d0430de49bfec5ad943fc130/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/XtxtUML.xtext#L469).

<hr>

@devaigergely81 and @kmate, what do you think of these solutions? @kmate, can you think of any other possibilities?

**Comment by kmate** [comment]
I do not recommend option 3 in general.

**Comment by devaigergely81** [comment]
I prefer solution 2. If this is an Xtext bug, it is worth filing a bug report or patch. If they fix this, we can simply remove the extra iteration suggested by solution 2.

**Comment by kmate** [comment]
The original implementation of `TypeUsageCollector` is very rigid and messy, indeed. I also suggest the same option as @devaigergely81. I don't think we should step this premature optimization now.

**Comment by djnemeth** [comment]
All right, I'll prepare a solution based on the second option.

However, I'm not sure if we should consider this a _bug_, at least not on Xtext's end. Apparently, the ominous grammar-level cross-references are used even in Xbase, as it can be seen for example in the [`XConstructorCall`](https://github.com/eclipse/xtext/blob/003a5602d3ddb86fd2204e4e6276e5b109ccdd89/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/Xbase.xtext#L261) parser rule. But instead of implementing a generalized method for this type of cross-references, they've chosen a workaround in form of another (seemingly complex), rule-specific type collection method – namely [`acceptPreferredType(EObject, EReference)`](https://github.com/eclipse/xtext/blob/003a5602d3ddb86fd2204e4e6276e5b109ccdd89/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java#L496) –, which is then used in case of an involved expression, [for example](https://github.com/eclipse/xtext/blob/003a5602d3ddb86fd2204e4e6276e5b109ccdd89/plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/TypeUsageCollector.java#L190) the aforementioned `XConstructorCall`.

And I'm concerned they have a good reason for that. As far as I know, the customizable parts of the framework dwell within the world of the EMF metamodel, whereas the problematic cross-references lie on a much lower abstraction layer.

Nevertheless, I'll open a ticket in Xtext's repository and ask the developers whether such generalization would be possible.
