### ISSUE TITLE
Transition names should be optional

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#23]
In the declaration of a transition:
```
transition init_A1 {
	from init;
	to A2;
}
```
It should be beneficial to be able omit the name, it can be generated from the from and to declarations.
The name should be in readable format, if the transition goes from `A` to `B` it should be `A_B`
If there are multiple transitions from `A` to `B` they should be labeled `A_B_n` where `n` is a number based on the order of declarations.

**Comment by devaigergely81** [comment]
For transitions other than init, it would be good to encourage users to invent meaningful names for transitions. Those can also be shown on the state machine diagram and help understanding the behavior.
What do you think, everyone?

**Comment by nboldi** [comment]
I think that it should be optional. The source state the target state and the event is usually enough to identify the purpose of the transition.

**Comment by devaigergely81** [comment]
Let's discuss this with the teams.

**Comment by GregoBalu** [comment]
But also if there are no names on transitions, for understanding you have to open that specific transition block and read the data. Further more you don't have a clue about what's the signal is, so you have to search that signal also, open it's block and read that also. While having named transitions, this can be achieved by not opening any blocks but reading the name.

**Comment by kovacsgabor** [comment]
This proposal does not seem supported by the teams. If our future users will complain about the inconvenience of mandatory transition names, than we will implement this, but until then, I close this issue.
