### ISSUE TITLE
CPP runtime coupling

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#232]
The CPP runtime should have the following properties:
- "runtime" folder should not contain generated files
- runtime configuration (like pool configuration) and initializing should go into a separate main file generated, although configuration which is tied to the objects themselves can stay in the object first
- runtimes should be compatible with each other, the code generation should not change because of different runtimes (example: Single threaded runtime also accepts pool configuration even if it discards it.)
- there will be multiple runtimes in the future, the threaded/non-threaded options does not make sense, we should select a runtime instead

**Comment by gerazo** [comment]
Note: We need a thread runtime and a non-threaded one (single threadedness is just a specific case of a threaded runtime)

**Comment by devaigergely81** [comment]
:+1:
