### ISSUE TITLE
Do not hardwire cpp compiler settings

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#234]
- Use cmake on generation instead of makefile
- Generate standard compliant code (not _DEBUG symbol) which compiles as C++11
- We should generate the same code for debug or release. This should be controlled when compiling the code with a cpp compiler
- Now we think that tracing can be part of debug compilation... it can be changed later to a TRACE def

**Comment by devaigergely81** [comment]
:+1:

**Comment by devaigergely81** [comment]
@gerazo, is this ready after the merge of the cpp_cmake branch?

**Comment by gerazo** [comment]
Yes. This is done by the cpp_cmake branch and is merged! :yum: 
As an extra (because of the undeserved popularity of Win) we now generate project for MSVC as well. Although we will only test on gcc and clang automatically, project members will also use MSVC for development so it will also work on that platform.
