### ISSUE TITLE
cpp testing

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#235]
How do we write test cases?
Do we compare raw output?
Do we interact somehow with the code?
Are we generating separate mains for test cases?

**Comment by devaigergely81** [comment]
My suggestion:
- Short term: Test cases are txtUML models, the test compiles these to C++ and checks if the generated code is accepted by the C++ compiler.
- Long term: Test cases are extended with main functions which run the generated C++ codes with input data/signals, and output data/signals are compared to predefined values in the test case.
- I **do not** recommend raw output comparison of generated C++ code.
