### ISSUE TITLE
InPort and OutPort in JtxtUML

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#239]
Based on @devaigergely81's proposal, the following two specific port types could be introduced in JtxtUML:

a)
`InPort<P>`, which would be equivalent to a `Port` which's required interface is `P` and provided interface is `Empty`.
b)
`OutPort<P>`, which would be equivalent to a `Port` which's required interface is `Empty` and provided interface is `P`.

They could still be behavior ports without the introduction of any new types as behavior ports are marked with an annotation.

**Comment by kovacsgabor** [comment]
Question: If we introduce this, will XtxtUML ports with `Empty` interfaces be translated to `InPort` and `OutPort`? Only matters if we ever want to read a JtxtUML code generated from XtxtUML.

**Comment by devaigergely81** [comment]
This would be syntactic sugar in JtxtUML, whereas the original port notation with possibly empty interfaces are part of the core language. I suggest translating XtxtUML to core language constructs.
