### ISSUE TITLE
Missing multiplicity handled incorrectly

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#241]
If association end multiplicity is omitted in XtxtUML, there is no error shown in the editor, but invalid JtxtUML code is generated and model export fails with an exception.
Two things need to be fixed:
- XtxtUML: Either make the multiplicity mandatory in the grammar or fix the Java code generation such that it generates `One` as default multiplicity.
- Model export should provide meaningful error message in case of problems in the model.

**Comment by djnemeth** [comment]
What a nasty bug indeed. I'm fixing the XtxtUML part ASAP.

**Comment by djnemeth** [comment]
What is the status of the model export part?

**Comment by kovacsgabor** [comment]
@nboldi, what can you say about the model export part of this issue? As I see, the X part is done.

**Comment by djnemeth** [comment]
Currently, the model exporter throws an exception and shows the problematic code snippet and the stack trace if an invalid (or not yet supported) model element is encountered, for example:

![model-exporter-error](https://cloud.githubusercontent.com/assets/13290204/17360352/731fd50e-596b-11e6-9a83-785aaf2559e5.png)

@devaigergely81, do you consider this enough to close this issue?

**Comment by djnemeth** [comment]
The team have decided that in the current state of the implementation, these kind of error messages are sufficient.
