### ISSUE TITLE
Association line touches independent class

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#242]
![diagrambug](https://cloud.githubusercontent.com/assets/7555116/13013715/dacb8344-d1b0-11e5-83f6-d7c901b75224.png)

@GregoBalu, @dobreffandras, please look into this!

**Comment by GregoBalu** [comment]
So I checked my part and the grid results are OK in a way that we would expect it. Somewhere in the calculation to pixel values should be some rounding errors I believe.

I haven't checked the papyrus part, so I'm not sure where does it go wrong.

Still I have thought of this for a while: if I (layout.visualizer) should return exact pixel values for everything. Currently the width/height of the boxes are altered by me anyway. Maybe I should be in charge of these so any placement issues should be considered my fault.

**Comment by GregoBalu** [comment]
This also leads us to better handling lines during the link arrange section. As I mentioned before we need methods to prefer certain routes over others. In this case the link should be in the middle of the corridor between the boxes using 2 turns in my opinion.
