### ISSUE TITLE
New repo structure

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#247]
Create new folder structure:
dev/ plugins releng tests features
examples/ demo tests

And adjust Jenkins to accommodate the new situation

**Comment by gerazo** [comment]
We still need to
- remove .settings
- move exmaples to demo folder

**Comment by kovacsgabor** [comment]
Do we need `.gitignore` files in every project? Woudln't it be simpler if we used the `.gitignore` file in the root folder to ignore every `bin`, `src-gen`, `gen` etc. folders globally?

**Comment by gerazo** [comment]
Well, we could do that. However, I wouldn't like to accidentally miss the creation of a gen folder where it is not supposed to be. The individual files are custom per project and only point to a certain place in a folder. They do not generally ignore every gen folder. I think it is better this way.

**Comment by gerazo** [comment]
demo examples should be: clock, machine, monitoring, pingpong, producer_consumer, train
The decision was to commit .settings still

**Comment by kovacsgabor** [comment]
What about the projects in which the `.settings` folder is already ignored?

**Comment by gerazo** [comment]
As far as I understand, the decision was that the project maintainer can decide to not commit the .settings if she/he sees a special reason for that. I consider that this is the case at these projects.

**Comment by gerazo** [comment]
https://github.com/ELTE-Soft/txtUML/pull/251 solved the remaining problem.
