### ISSUE TITLE
Class name cannot be referenced in action code of state or transition

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#25]
```
model PerformanceTestModel {
	class A {
		state S {
			entry {
				A a;
			}
		}
	}
}
```

The error message is the following:
```
Type mismatch: cannot convert the expression to Class	PerformanceTestModel.xtxtuml
```

**Comment by nboldi** [comment]
It seems that the name similarly cannot be referenced in any place.

**Comment by nboldi** [comment]
```
model ErrorReportingModel {
	class A {
		void eatA(A a) {
		}
	}
}
```

**Comment by devaigergely81** [comment]
It can be referenced using a qualified name:
~~~~
	class A {
		state S {
			entry {
				ModelName.A a;
			}
		}
	}
~~~~

**Comment by nboldi** [comment]
It is not expected that the name of the model must be used to qualify class names inside the model.

**Comment by devaigergely81** [comment]
I agree that is why I left the issue open. :) I just wanted to post the workaround.

**Comment by devaigergely81** [comment]
Dávid, if this is hard to fix, remove the milestone! Thx.

**Comment by kmate** [comment]
It seems that `XtxtUMLImportNormalizer::deresolve` runs into and endless loop while trying to deresolve model name `M` against imported namespace prefix `java.lang`.

**Comment by kmate** [comment]
Steps to reproduce:

1. Start with the following source:

~~~~~
model M { class Test {
}}
~~~~~

2. Hit Ctrl+Space inside the inner brackets to get content assist. Eclipse will freeze because the infinite loop in the name deresolution.
