### ISSUE TITLE
Delete importing.uml2?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#252]
This plugin was once a research project, which was about to generate (J)txtUML code (that time only JtxtUML existed) from exported EMF-UML2 models.

Now this plugin is not only old and unused but outdated. Both our EMF-UML2 model generation process and the JtxtUML syntax (this plugin's input and output) changed so much that it does not seem to work anymore.

However, it still exists in our repo, is part of the txtUML feature, and compiles with every Jenkins build. Unnecessarily, in my opinion.

**Comment by kovacsgabor** [comment]
What do you think, @ELTE-Soft/all?

**Comment by dobreffandras** [comment]
It depends on which is easier if we ever will have the interest and resource for this feature: Continue or recreate?

**Comment by devaigergely81** [comment]
I suggest deleting it. It is preserved by the history of the repo and also in our internal SVN.

**Comment by kovacsgabor** [comment]
The whole project changed so much since the last update of this project that I don't think it could help us if we ever want to implement the UML -> JtxtUML conversion.

**Comment by kovacsgabor** [comment]
Without further opposition, I consider this proposal supported.
