### ISSUE TITLE
Remove "generate state machines automatically" check box?

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#257]
Branch: deva/sm-diagrams
Since state machine diagram descriptions are now supported, I suggest removing the check box from the dialog box.
@GregoBalu, @dobreffandras, what do you think?

**Comment by dobreffandras** [comment]
Yes, it should be removed. I planned to remove it as soon as #250 is solved.

**Comment by devaigergely81** [comment]
Solved in https://github.com/ELTE-Soft/txtUML/commit/8e36a1eb49d0aab5d019faeb9d360988a53fea3f.
