### ISSUE TITLE
The expression `this` cannot be typed in action of state or transition

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#26]
The following code:
```
model ErrorReportingModel {
	class A {
		state A1 {
			entry {
				send new S() to this;
			}
		}
	}
	signal S;
}
```
Gives the error message
```Type mismatch: cannot convert the expression to Class```

**Comment by devaigergely81** [comment]
Similarly to #25, the workaround is qualifying:
~~~
    class A {
        state A1 {
            entry {
                send new S() to ModelName.A.this;
            }
        }
    }
~~~

**Comment by devaigergely81** [comment]
Dávid, if you think this is not feasible quickly, please remove the v0.2.0 milestone from this issue.

**Comment by djnemeth** [comment]
Unfortunately, I won't be able to implement this in time, therefore I've removed the milestone.
