### ISSUE TITLE
Create template proposals for structural elements

### ISSUE THREAD

**Issue by kmate** [ELTE-Soft/txtUML#27]
For more information, see https://eclipse.org/Xtext/documentation/304_ide_concepts.html#templates.

**Comment by devaigergely81** [comment]
Is this about adding code templates to the actual position in the editor? If yes, the proposals:
  * class
  * state with or without entry/exit declaration
  * transition with or without effect declaration

**Comment by kmate** [comment]
Yes, it is. In other editors it is often called as "code snippets". It provides editable placeholders in an inserted template.

**Comment by klariann** [comment]
The link in the first comment is outdated, the working link is: [https://eclipse.org/Xtext/documentation/310_eclipse_support.html#templates]

**Comment by klariann** [comment]
If you want to add new template proposals, open the user eclipse, and go to  Window > Preferences. Write Templates to the searching bar, and select XtxtUML. Add the proposals you want, and then click to export templates. To automatically add these templates to TxtUML tools, you have to copy the templates.xml file to\txtUML\dev\releng\hu.elte.txtuml.target in your project, and open the file to add an id for each template. (These ID-s must be different.) If you add new proposals as I explained you have to add id for all proposals, not just for the new ones. You can also add new proposals, if you write the templates directly into the templates.xml file. In this case of course, you don't need to add id for the old ones.
