### ISSUE TITLE
Export class constructors

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#273]
That operations which are signed as constructor should be exported as c++ constructor with adequate parameters and activities.  The operations which initializes the state machine should be executed at all constructors.

**Comment by devaigergely81** [comment]
I'm not sure what do you mean by "operations which initializes the state machine", but please take into account that the state machine starts its functioning only when the start behavior action is executed, and not right after creation of the object.

**Comment by nagyandras95** [comment]
It just fills the transition map and sets up the thread pool id but it doesn't start the state machine. The Runtime will not start to process its events until the state machine isn't started.

**Comment by devaigergely81** [comment]
I see, OK.
