### ISSUE TITLE
Check java reserved names

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#29]
`state final;` is a perfect state declaration in XtxtUML, but the generated code is bogus:
```
public class final extends StateMachine.State {}
```

**Comment by nboldi** [comment]
It would be even nicer if we allow this names but postfix the generated java name with an underscore.

**Comment by devaigergely81** [comment]
The automatic postfixing is dangerous: what if there is another attribute with the postfixed name. It would also complicate XtxtUML <-> JtxtUML <-> UML round trip conversions.
My suggestion is to simply prohibit Java keywords by XtxtUML validation.

**Comment by nboldi** [comment]
I think it is perfectly OK to declare something like `state final;` invalid.
@djnemeth, What is the status of this issue?

**Comment by djnemeth** [comment]
Validation of Java reserved words in XtxtUML identifiers is under development in branch [xtxtuml-validation-fixes](https://github.com/ELTE-Soft/txtUML/compare/xtxtuml-validation-fixes).
