### ISSUE TITLE
Prepare demo examples for 0.4.0

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#293]
- Remove `hu.elte.txtuml.examples.` prefix from project and package names.
- Restructure package structure so that X and J models and different variants of the model (eg. the 3 Machine variants) are separated, and each model is packaged together with its diagrams and tests.

**Comment by kovacsgabor** [comment]
Should test examples be renamed as well?

**Comment by devaigergely81** [comment]
Renaming the test examples is not urgent, they will not be part of the release.
