### ISSUE TITLE
Change request about the export of if-then-else

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#305]
~~~~
class A {
	void f() {
		int i;
		if(i == 0) {
			i = 2;
		} else {
			i = 4;
		}
	}
}
~~~~
![ifproblem](https://cloud.githubusercontent.com/assets/7555116/13815981/f119889e-eb8c-11e5-86c6-e8fc13f883ff.png)

An if-then-else is exported as a conditional node with two clauses. Each clause has a *test*, which is responsible for evaluating the condition of the clause and a decider (an output pin) that specifies the result of the computation. Since we want to avoid duplicate condition evaluations, the test of the then clause writes the result into a variable, which is then negated in the test of the else clause.

This causes data dependency between the two tests, which is represented by the object flow highlighted in the picture above. When determining the correct order in which the tests should be generated into the C++ code, this data dependency needs to be analysed. As a general design decision, we want the exported models to be explicitly structured, so that such data dependency analysis is never required. (That might be later extension.)

Suggestion: Use one single test for all clauses, that creates one boolean local variable per clause, writes them (to set the values) and reads them (to provide output pins for the deciders).

Another request: the names of these variables should be Java/C++ identifiers, the # symbol currently causes problems.

In case an if- else if - else if - .... - else structure, currently multiple conditional nodes are generated embedded in each other. It would be nicer to have one single conditional node with many clauses. But this is not a blocking issue.

**Comment by nboldi** [comment]
In the new export architecture, the expression is exported outside of the if statement, and the tests only contain one readVariableAction and the logical negation in the case of the second one.

**Comment by nboldi** [comment]
It would be problematic to generate a single If statement, because the semantics are not the same. Clauses of ConditionalStatements are not checked sequentially. The only possibility would be to negate all previous tests in a test.

So 
```
if (a) {
} else if(b) {
} else if(c) {
} else {
}
```
would become
```
if (a) {
}
if(b && !a) {
}
if(c && !b && !a) {
}
if (!a && !b && !c){
}
```
After that it is up to the C++ code generation to reverse this transformation. Note: this is also currently done for a simple if-then-else statement.

**Comment by nboldi** [comment]
@nagyandras95, what is your opinion?

**Comment by nagyandras95** [comment]
I think this solution would be appropriate for if - else if .. statements. It was our notation with @devaigergely81 too.

**Comment by devaigergely81** [comment]
In the original issue description we mentioned 3 problems:
1) avoid data dependency
2) naming
3) flattening if-elseif-elseif-...-else structures

1: As far as I understand @nboldi's response, if the variable is set outside the tests, then the data dependency highlighted on the image above goes away. Is it the case?
2: This seems trivial to change.
3: Since UML's conditional node has no ordering between the clauses, and we do not want to analyse the conditions, even for a two-way branch we will generate something like this:
````C++
a = cond1(...);
if(a) { ... }
if(!a) { ... }
`````
Note that the order of the two branches might be reversed.
If we have more than two branches, there are options:
* Export a hierarchy of  two-way ifs:
```C++
a = cond1(...);
if(a) { ... }
if(!a) { 
  b = cond2(...);
  if(b) { ... }
  if(!b) { ... }
}
````
* Export a flat multi-branch:
```C++
a = cond1(...);
b = !a && cond(2);
c = !b;
if(a) { ... }
if(b) { ... }
if(c) { ... }
````
We have to use shortcut conjuction, so that `cond2` is not called if `cond1` returns true, so the second solution is just doing a little bit more work. However, if the condition evaluation is a computation split into several instructions, then this gets more complicated.

All-in-all, even if the flattened multi-branch leads to cleaner model, the hierarchy of two-way if's seems to be safer and possibly faster.

**Comment by nboldi** [comment]
I agree with all three conclusions.
