### ISSUE TITLE
Rename `assoc` and `port` methods?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#306]
As both of these are used to get some kind of property of a model object and both are written in XtxtUML as `->`, it would be sensible to rename both functions as `get` or something like that.

**Comment by kovacsgabor** [comment]
What do you think, @ELTE-Soft/all?

**Comment by GregoBalu** [comment]
On the other hand it would also mean that they are longer to write. These are frequently used keywords. I wouldn't mind creating a ```getAssociations()``` method but for easy-to-use and legacy reasons I would also keep the old ones as well.

**Comment by kovacsgabor** [comment]
My proposal was about to rename both methods as `get`. Not `getAssociation` or `getPort`, simply `get`. For both of them. Because they the same symbol in XtxtUML, it would make sense to give the same name to them in JtxtUML. Also, as you said, these are very frequently used so I think they could be named so simple as `get`.

**Comment by GregoBalu** [comment]
I see. This is reasonable.
Wouldn't it be less understandable this way? To differentiate between them, when reading a code that uses this syntax?

**Comment by kovacsgabor** [comment]
You cannot differentiate between them in X. And I do not consider this is a major requirement as both are some kind of properties, identified by their types.

**Comment by kovacsgabor** [comment]
@ELTE-Soft/all, any other opinions?

**Comment by nboldi** [comment]
I think the syntax should not change. This issue should be closed.
