### ISSUE TITLE
Constructor call when create a Signal

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#308]
``
public class S1 extends Signal { 
public S1(int i) {
this.i = i;
}
}
``
``
S1 s = new S1(5);
``

![singal_error](https://cloud.githubusercontent.com/assets/15140899/13957580/2ed047e4-f04d-11e5-82c4-2a137674259d.png)
Although signal `S1` has a constructor parameterized with an integer, it seems that there is no a CallOperationAction which invokes it.

**Comment by nboldi** [comment]
Constructors are only generated for UML Classes, because UML Signals can only have attributes.

**Comment by nagyandras95** [comment]
But in txtUML we could create a constructor for a signal to set its properties easily. In addition it is generated in xtxtUML automatically when we add a property for a signal. Do you mean it is not allowed in UML standard? Constructor parameters are also generated in C++ code at this moment but as I see they should be removed.

**Comment by nboldi** [comment]
Yes, there is no ownedOperation feature on Signals. It could be solved by generating a class for each signal that contains a static method to generate the given signal. This static method could be used like a constructor.

**Comment by nboldi** [comment]
Or if we only allow simple assignments in the signal constructor, they could be performed at the call site.

**Comment by nagyandras95** [comment]
Or is it not possible to export the property setting as a `AddStructuralFeatureValueAction` instead of constructor call?

**Comment by nboldi** [comment]
If we validate that a constructor does only contain very simple assignments to members, it is a possible way to implement this.
