### ISSUE TITLE
Foreach loop exported wrong order

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#315]
<img width="334" alt="foreach_problem" src="https://cloud.githubusercontent.com/assets/15140899/14308405/3f0d8420-fbd6-11e5-9d45-5704c305efa7.png">

The `ReadLinkAction` activity should be prevented the `ExpansionRegion` because I need its result for the iteration.

**Comment by nboldi** [comment]
You mean that the ReadVariableAction should be outside and before the expansion region?

**Comment by nagyandras95** [comment]
I just mean the ReadLinkAction should be before the ExpansionRegion in the sequence node.
