### ISSUE TITLE
LinkAction problems

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#317]
- The `ReadLinkAction` should contain one more `LinkEndData` whose `End` defines the read property and it contains no value.
- It should be defined as a standard function for `selectAny()` whose parameter contains the result of `ReadLinkAction` and it returns only one object.
- The `CreateLinkAction` contains two unnecessary `ValuePin`s.

**Comment by nboldi** [comment]
@devaigergely81, @nagyandras95, how can I create a suitable selectAny function? It must have a type parameter, to work with all possible types of elements, right? Do we have examples for that?

**Comment by devaigergely81** [comment]
UML has templates, I hope Papyrus also supports them!
