### ISSUE TITLE
Composition is not appearing on the generated Diagram

### ISSUE THREAD

**Issue by dobreffandras** [ELTE-Soft/txtUML#318]
Compositions in the model are not appearing on the diagram

```java
class ExampleComposition extends Composition {
	  class a extends Container<A> {}
	  class b extends Many<B> {}
}
```
Result can be seen in this picture:
![composition](https://cloud.githubusercontent.com/assets/14291673/14369043/2d65ac5a-fd22-11e5-955d-f254efed6485.png)

**Comment by dobreffandras** [comment]
Papyrus generates association, composition and aggregation using the UML model. 
Currently the uml export generates associations in all cases. ( @nboldi is it true?)
If the "Aggregation" attribute of the OwnedEnd of the Association is set to either "Shared" or "Composite", it will be automatically visualized as aggregation or composition.

**Comment by nboldi** [comment]
I think that it is done currently, and it surely will be done in the refactored version. I don't know much about the visualization. Please check if the generated model has the composite flage.

**Comment by dobreffandras** [comment]
Currently the neither of the association ends have this attribute set to `Composition`, see the picture.

![composition2](https://cloud.githubusercontent.com/assets/14291673/14777080/f4e7bb8c-0aca-11e6-9abd-dbfed22af1f2.png)

But let's wait the refactored version as you mentioned on the meeting.
