### ISSUE TITLE
XtxtUML runtime depends on UI components

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#320]
In the current implementation, the XtxtUML runtime [depends](https://github.com/ELTE-Soft/txtUML/blob/db9edb14ee264aa6c5c92c68f08962fcab1feb37/dev/plugins/hu.elte.txtuml.xtxtuml/META-INF/MANIFEST.MF#L23) on components of the Xtext UI module. As far as I know, this makes headless builds (e.g. unit testing such UI-dependent classes) impossible. @gerazo, please correct me if I'm wrong.

**Edit:** Corrected *XtxtUML UI module* to *Xtext UI module*.

**Comment by gerazo** [comment]
You are right. However, I can't see hu.elte.txtuml.xtxtuml.ui in the manifest of hu.elte.txtuml.xtxtuml. I only see dependency in the pom.xml but it is for building reasons (cleaning the generated folder synchronuously between the two projects). I am probably missing something.

**Comment by djnemeth** [comment]
Sorry, you're right. It [depends](https://github.com/ELTE-Soft/txtUML/blob/master/dev/plugins/hu.elte.txtuml.xtxtuml/META-INF/MANIFEST.MF#L23) on UI components of *Xtext* itself.

**Comment by gerazo** [comment]
I've checked and the Xtext generated manifest does not depend on these UI components, so we added them, so it's our fault. :facepunch:
