### ISSUE TITLE
Revert the removal of getSignal parameter

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#322]
In #139, we decided to remove the parameter of `getSignal` because it seemed unnecessary with the JDT translation. However, we agreed to forbid casting in (J)txtUML models and therefore the use of `getSignal` without a parameter is problematic at least because the user would be confused where to use and where not to use casting. Despite the fact, that
```java
((MySignal) getSignal())
```
in the current syntax has exactly the same result as
```java
getSignal(MySignal.class)
```
in the old and future syntax because `getSignal` is generic and it casts its result to its type parameter.

**Comment by devaigergely81** [comment]
I agree.
