### ISSUE TITLE
Change syntax of model declarations?

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#328]
In the current implementation, the XtxtUML runtime depends on components of the Xtext UI. See #320. One notable example for this dependency is [XtxtUMLPackageNameCalculator](https://github.com/ELTE-Soft/txtUML/blob/0d885491df573c697b7139a1d5779aff9e5510e0/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/naming/XtxtUMLPackageNameCalculator.xtend#L14), which is [used](https://github.com/ELTE-Soft/txtUML/blob/0d885491df573c697b7139a1d5779aff9e5510e0/dev/plugins/hu.elte.txtuml.xtxtuml/src/hu/elte/txtuml/xtxtuml/jvmmodel/XtxtUMLJvmModelInferrer.xtend#L69) by the model inferrer to calculate the fully qualified name of the JVM element representing a model declaration, from which a *model-info.xtxtuml* file will be generated, eventually translating to a *package-info.java* file.

The current syntax of model declarations is the following:

```
'model' name=STRING? ';'?
```

That is, a `model` keyword followed by an optional string literal representing the name of the model (which is used during UML export if I recall correctly) and an optional semicolon at the end. It can be seen that no fully qualified name is specified.

In XtxtUML files containing a package declaration (as in Java), the package name is actually the name of the whole file as a container. This is leveraged by the default qualified name calculator, which computes the qualified name of an XtxtUML element by traveling through its containers and appending their names, yielding a fully qualified name if a package declaration is present.

The easiest way to eliminate the aforementioned problematic dependency would be to change the syntax of model declarations such that the package name is included as well. In this way, the default qualified name calculator could be used instead of the UI-specific package name calculator. This would also bring [*J*](https://github.com/ELTE-Soft/txtUML/blob/db9edb14ee264aa6c5c92c68f08962fcab1feb37/examples/demo/clock/src/clock/j/model/package-info.java) and *X* syntaxes closer.

I propose the following alternatives:

1. alternative
<pre>
    <b>model</b> foo.bar.baz <b>named</b> "BazModel";
</pre>

2. alternative
<pre>
    <b>model</b> foo.bar.baz <b>as</b> "BazModel";
</pre>

3. alternative
<pre>
    <b>model</b> "BazModel";
    <b>package</b> foo.bar.baz;
        <i>// or in reverse order</i>
</pre>

4. alternative
<pre>
    <b>model</b> foo.bar.baz {
        <b>name</b> "BazModel";
    }
</pre>

5. alternative
<pre>
    <b>model</b> "BazModel" {
        <b>package</b> foo.bar.baz;
    }
</pre>

#217 should be considered too. @ELTE-Soft/all, what do you think?

**Comment by gerazo** [comment]
1 and 2 are still far from the J version. I would support 3,4,5 but the closest would be 3 in reverse oder.

**Comment by devaigergely81** [comment]
I prefer 4 or 5, but it would be good to avoid the `model` keyword (see #217). So what about this:
~~~
package foo.bar.baz {
    name "MyModel"
}
~~~

Another possibility is to remove `model.info` completely and keep only the Java variant.

**Comment by kovacsgabor** [comment]
I support @devaigergely81's proposal (with a semicolon at the end of the second line) because it avoids the `model` keyword and lets us make the name of the model optional (it is also optional in J).

**Comment by djnemeth** [comment]
For me, it feels a bit confusing to use the `package` keyword both for model and package declarations. 

How should we decide if a model declaration without the optional name part is not actually a conventional package declaration? Should we check if it was defined in a file named exactly *model-info.xtxtuml*? Or a package declaration should be considered a model declaration iff the given file contains no other elements? We would also need to validate that an actual package declaration doesn't have a name.

I mean, from a user's point of view, it could be confusing that there's only a marginal difference between a model and package declaration.

**Comment by djnemeth** [comment]
I also find using curly braces a bit inconsistent here. In other elements of XtxtUML, curly braces indicate the boundaries of the given element. In this case, however, a model encloses all other elements defined in the given package, not just its (optional) name. Generally I would prefer to use a syntax which is closer to a conventional package declaration, just like it is in the current implementation.

**Comment by kovacsgabor** [comment]
I do not know whether this helps or not, but the Java module system (planned to be released in Java 9) has a similar syntax: https://en.wikipedia.org/wiki/Java_Module_System

**Comment by dobreffandras** [comment]
It is sad, that we have to get rid of the `model` keyword. I think that the syntax suggested by @devaigergely81 is not so ovious to tell the user that it IS the model. So without the model keyword I would suggest to use only the Java variant of `model.info`. It is only 2 lines of code, so it is not a big deal to a hater of the Java syntax, but it is clear enough, that the annotated packge is the model.

**Comment by djnemeth** [comment]
The team agreed on:
- keeping model declarations in XtxtUML (i.e. **not** using *package-info.java* files instead)
- with the following syntax:
<pre>
    <b>model-package</b> foo.bar.baz <b>as</b> "BazModel";
</pre>

This will resolve #217 too.
