### ISSUE TITLE
Unnecessary opaque action causes problems

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#329]
<img width="608" alt="opaque_action_problem" src="https://cloud.githubusercontent.com/assets/15140899/14486579/fc602e2e-015d-11e6-96a6-423b78dbad93.png">

The highlited `InputPin` should be linked with the result of `ReadStructuralFeatureAction` instead of the unknown `OpaqueAction`. This model was written in xtxtuml so this problem might be caused by the generated code because the `ValueOf..` statements are not valid in the model.

**Comment by nboldi** [comment]
We should discuss how to handle automatic `toString` calls and method calls like `Integer.valueOf()` next meeting.
