### ISSUE TITLE
Implement signal inheritance in XtxtUML

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#334]

**Comment by djnemeth** [comment]
Signal inheritance in XtxtUML hasn't been implemented yet. As we are generating their constructors from their attributes, in case of inheritance we would need to ensure that each base signal gets initialized *before* its derived signals.

I thought this is not achievable without heavy modifications the two-phase inference process we currently use (see #313), but now I believe this might be solvable after all.

Implementing signal inheritance would also require to ensure that type computation of the signal access expression (`sigdata`) is correct.

**Comment by kovacsgabor** [comment]
I see that this is much more complicated than how much it would help so I set this as a low priority issue.
