### ISSUE TITLE
If a port is defined after it is referenced in a transition in X, the generated J code is erronous

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#336]
It should be either fixed or validated.

**Comment by djnemeth** [comment]
I believe this is due to #313, which is fixed in #314.

**Comment by kovacsgabor** [comment]
That is possible, I found it when testing #319, so I did not check this on a branch that includes #314.

**Comment by kovacsgabor** [comment]
It is indeed fixed by #314.
