### ISSUE TITLE
Inconsistent handling of entry and exit actions in initial states, in X vs J input files

### ISSUE THREAD

**Issue by darvasa** [ELTE-Soft/txtUML#339]
While Xtxtuml grammar allows entry and exit actions to appear in initial states, it leads to an error message in the generated Jtxtuml file.

**Comment by kovacsgabor** [comment]
#319 was merged a few hours ago. It solved this problem among many others.

**Comment by djnemeth** [comment]
(To be more precise, we only introduced a validation rule against this, the grammar itself hasn't been changed.)
