### ISSUE TITLE
ModelExecutorThread.shutdown should block until terminated

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#34]
I created a patch that solves this issue
[ModelExecutorThread.java.txt](https://github.com/ELTE-Soft/txtUML/files/15018/ModelExecutorThread.java.txt)

**Comment by kovacsgabor** [comment]
According to a similar structure used in the ExecutorService interface (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html), I think it would be better if shutdown did not block. I introduced the awaitTermination method instead.
