### ISSUE TITLE
Declaration of protected member causes error in generated Java file

### ISSUE THREAD

**Issue by darvasa** [ELTE-Soft/txtUML#344]
The following valid xtxtuml code:
```
   package [...]
   class Test {
      protected String a;	
      protected void foo() { }
   }
```
Causes error "Invalid modifier. Only private and public are allowed on all elements." in the generated Java file. 

You can easily reproduce it, for instance, in the monitoring example by making Alert.max protected.

**Comment by kovacsgabor** [comment]
I think we should allow protected visibility in txtUML models and therefore I consider this a JtxtUML validation problem and an XtxtUML one.
