### ISSUE TITLE
Error: The method +(int) is undefined

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#36]
When trying to compile the following lines of code in an effect:
```
int y = 3;
int x = y + 1;
```

Where `numForward` is an attribute in the current class. However it is also produced when local variables are used.

**Comment by nboldi** [comment]
It seems that no operator is working in these context, not even `==`.

**Comment by djnemeth** [comment]
The current XtxtUML implementation uses the default operator mapping, defined in Xbase, to map operators to correspondent extension methods. These extension methods are defined in bundle `org.eclipse.xtext.xbase.lib`, but this bundle was not listed as a dependency of the problematic txtUML project, therefore the errors.

As the missing bundle has been added to the project dependencies, I'm closing this issue.
