### ISSUE TITLE
Prepare demo examples for 0.5.0

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#365]
- [x] All demos should have layout descriptions for all relevant diagrams (both X and J).
- [x] Provide a meaningful naming convention to diagram layout descriptions and configurations which is then followed in all demo examples.
- [ ] Remove warnings (with `@SuppressWarnings("unused")` in case of the airport example where necessary).
- [ ] Mark the airport example as one that is under development (to explain the code parts in comments and `@SupressWarnings("unused")` annotations)
- [x] Rename the airport example to begin with a lowercase letter.
- [x] Rename the 'dokumentacio' folder in the airport example as 'documentation' or remove it entirely.
- [ ] Split the X version of the pingpong and clock examples into multiple files.

**Comment by djnemeth** [comment]
For some strange reason, the XtxtUML tester executions introduced in 37491e3 are missing now. I added a list entry for fixing this.

**Comment by djnemeth** [comment]
I have created branch *[v050-examples-prep](https://github.com/ELTE-Soft/txtUML/tree/v050-examples-prep)* for the remaining points.
