### ISSUE TITLE
Popup did not appear on compilation errors

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#39]
After a few focus switches between the eclipse and other programs it appeared.

![popup](https://cloud.githubusercontent.com/assets/2959869/10583408/1451fec4-768d-11e5-9939-4b3b423f8b90.png)

**Comment by devaigergely81** [comment]
What is the popup that you expected? Is this reproducible?

**Comment by nboldi** [comment]
I think it was a validation error. (Collection cannot be used.) But I will try to reproduce it.

**Comment by nboldi** [comment]
I got this problem with other kind of messages. It may be an editor bug.

**Comment by nboldi** [comment]
If it is an editor bug, we don't have the time to deal with it.
