### ISSUE TITLE
XtxtUML models with subpackages are not browsable in txtUML wizards

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#393]
Steps to reproduce:

1. Create a new txtUML project.
2. Create a new XtxtUML model inside the previously created project.
3. Create a new (sub)package inside the previously created model.
4. Open either the *Generate C++ code from txtUML* or the *Generate diagrams from txtUML* wizard, select the project created in step 1 and try to select the model created in step 2 by the *Browse...* option. Notice that it's not listed.

For an additional example, consider the following package structure:
```
model
├── foo
├── bar
|   └── foo
└── foobar
    └── foo
        └── bar
```
In this case, packages `model.foo`, `model.bar.foo` and `model.foobar.foo.bar` are selectable as models, whereas package `model` (the actual model) is not.

**Comment by nagyandras95** [comment]
The `PackageSelectionDialog` is configured to hide empty packages and somehow it recognizes the model package as empty in this case but if we eliminate this option it will be browsable .

**Comment by djnemeth** [comment]
Thanks for the info!
