### ISSUE TITLE
Can't generate class diagrams from XtxtUML models

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#394]
Steps to reproduce:

1. Open the *Generate diagrams from txtUML* wizard.
2. Select any of the demo example projects.
3. Select the corresponding XtxtUML model.
4. Add the corresponding class diagram description (*X«DemoName»ClassDiagram*).
5. Click on *Finish* and notice that the opened Papyrus diagram is empty.

It seems this issue occurs only in case of class diagrams of XtxtUML models. JtxtUML models and diagrams are apparently unaffected, and state machine diagrams from XtxtUML models can also be visualized.

**Comment by dobreffandras** [comment]
I've made some debugging and realised that the model itself is not included in the txtUML-Uml2 mapping  (saved to the .mapping file).
