### ISSUE TITLE
UML export fails when try to export foreach loops which iterates on association ends

### ISSUE THREAD

**Issue by nagyandras95** [ELTE-Soft/txtUML#396]
I consider constructions like this:

`for (Type t in this->AssocioationName.End) {..}`

**Comment by nboldi** [comment]
When changing the api model in the future, please add the new classes with their qualified name to the stdlib model.

**Comment by nagyandras95** [comment]
OK, then I see what the problem was. We will take into consideration that in the future. Thanks for resolving.
