### ISSUE TITLE
Layout definition for state machines

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#4]
Currently, it is possible to define the layout of class diagrams. This should be possible also for state machines.

**Comment by nboldi** [comment]
@devaigergely81, @dobreffandras, is it solved with the merge of deva-sm?

**Comment by dobreffandras** [comment]
Hierarchy is not yet complete, if I'm right. @gergobalu ?

**Comment by GregoBalu** [comment]
Yes, however this issue is more about the ability to define any kind of layout on state machine diagrams, which is possible with deva-sm branch merged in (flat diagrams, using '... extends StateMachineDiagram<...>' ).
The hierarchy and the new layout syntax is present in #214 .
