### ISSUE TITLE
Wrong typing of subexpressions

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#405]
The following expression results in a double value: `-1 * world.v / (1 - (world.h/1000)*(world.h/1000))`

Double inputs are incorrectly converted to ints in the process:
```
int temp3 = 1;
int temp4 = (temp3 * world_us0->v);
int temp5 = (world_us0->h / 1000);
int temp6 = (world_us0->h / 1000);
int temp7 = (temp5 * temp6);
int temp8 = (1 - temp7);
int temp9 = (temp4 / temp8);
```

The conversion causes a compilation failure by the way.

**Comment by nagyandras95** [comment]
As the UMl model, the result type of 
`int temp4 = (temp3 * world_us0->v);` 
is Integer and I don't have any information about the type of right operand in that case. I can find it but it is a bit complicated. i think the UML export should be reviewed first.

**Comment by nboldi** [comment]
Yes, the problem is in the export. Currently we only have `IntegerOperations` class in the standard library that defines primitive operations and subsequently operations done on real arguments are also exported as such. I propose extending the standard library with `RealOperations`, defining the operations that are allowed on real arguments.

**Comment by djnemeth** [comment]
See #429.
