### ISSUE TITLE
Numeric expression is accidentally converted to string

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#409]
The generated code for the expression `world.v * (world.h*world.h/500000 + world.h/500 - 2)` is
```
int temp3 = (world_us0->h * world_us0->h);
int temp4 = (temp3 / 500000);
std::string temp5 = conversion::to_string(temp4);
int temp6 = (world_us0->h / 500);
std::string temp7 = conversion::to_string(temp6);
std::string temp8 = concat(temp5,temp7);
int temp9 = (temp8 - 2);
```
It seems that the `+` operator is used as concatenation.

**Comment by nagyandras95** [comment]
As I see this issue arises from UML export becasue toString and concat are generated.
![concat_error](https://cloud.githubusercontent.com/assets/15140899/17279245/dd94b8bc-576f-11e6-9a63-d04634793be3.png)
