### ISSUE TITLE
Use :: for qualified names instead of .

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#41]
The same `.` operator means different things, so `this->PerformanceTestModel.AB.a.selectAny()` must be written like `(this->PerformanceTestModel.AB.a).selectAny()`, that is strange. It would be nice to use double colon instead in qualified names.

**Comment by devaigergely81** [comment]
It has already been discussed to use `::´ for qualified names instead of `.´, but the implementation has not been completed yet.

**Comment by djnemeth** [comment]
It has been discussed by the team that `.` will be used in qualified names instead of `::`. See #204.
