### ISSUE TITLE
Negative literals are positive in generated C++ code

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#410]
From the expression `signal.h < 1 && signal.v < -10` the following code is generated:
```
bool temp1 = (signal_us0->h < 1);
int temp2 = 10;
bool temp3 = (signal_us0->v < temp2);
bool temp4 = (temp1 && temp3);
```
It is clear that the negative sign is ignored. The UML model is correct, so the problem is in the C++ code generator.

**Comment by nagyandras95** [comment]
As I know [my last PR commit](https://github.com/ELTE-Soft/txtUML/pull/382/commits/24fb9446dee11f1c80ee76e08c913d90ab611c31) resolves this problem. Did you try it on master?

**Comment by nagyandras95** [comment]
I get the following code in similar case:  `boolean l = trigger.alma < 1 && trigger.alma < -10;`
```
bool l_us0;
std::shared_ptr<S_EC> temp0 = std::shared_ptr<S_EC>(new S_EC(static_cast<const S_EC&>(e_)));
bool temp1 = (temp0->alma < 1);
std::shared_ptr<S_EC> temp2 = std::shared_ptr<S_EC>(new S_EC(static_cast<const S_EC&>(e_)));
int temp3 = -10;
bool temp4 = (temp2->alma < temp3);
bool temp5 = (temp1 && temp4);
```

**Comment by nboldi** [comment]
It is indeed fixed now.
