### ISSUE TITLE
Associations are not shown on class diagrams generated from XClock and XPingPong

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#413]
Steps to reproduce:

1. Open the *Generate diagrams from txtUML* wizard.
2. Select the *clock* or the *pingpong* demo project.
3. Select the *XClock* (*clock.x.model*) or the *XPingPong* (*pingpong.x.model*) model.
4. Add the corresponding class diagram description (*XClockClassDiagram* or *XPingPongClassDiagram*).
5. Click on *Finish* and notice the lack of displayed associations.

It seems the *J* counterparts of these models are unaffected.

**Comment by GregoBalu** [comment]
I guess these issues are not visual-side problems, as it only happens on X models. For the visualization it should not matter whether the source was in X or J, it's already one abstraction above and is working with uml elements (ecore and own).
I think this should be some X->J problem or, X->(J)->UML.
Same ~~in english~~ for #412 .

**Comment by dobreffandras** [comment]
Yes you're right. This is an export problem indeed. It depends on the structure of the X model. If the whole model is in one package there is no problem. But if there are several packages (eg. by XClock or XPingpong) the associations will not be written into the the txtUML-UML2  mapping. Any idea @nboldi ?

**Comment by djnemeth** [comment]
Fixed by #418.
