### ISSUE TITLE
Can't generate C++ code from several demo models despite defined configurations

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#414]
Steps to reproduce:

1. Open the *Generate C++ code from txtUML* wizard.
2. Select the *clock* or the *machine* demo project.
3. Select the *Clock* (*clock.j.model*) or the *XClock* (*clock.x.model*) or the *Machine3* (*machine3.j.model*) or the *XMachine3* (*machine3.x.model*) model.
4. Add the corresponding deployment configuration (*ClockConfiguration*, *XClockConfiguration*, *Machine3Configuration* or *XMachine3Configuration* respectively).
5. Click on *Finish* and notice the variety of displayed error messages.

**Comment by nagyandras95** [comment]
It is because of the unsupported language constructs like comprehensive Collection support which include lambda expressions too. The ports and connectros are also unsupported so we cannot resolve this issue soon.
