### ISSUE TITLE
Rework the 'execution' element of XtxtUML

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#430]
As #331 has changed the model execution interface significantly, XtxtUML executions in their current state cannot be run. We have to adapt this element to make it directly executable while keeping its syntax and semantics as simple as possible. The main idea is that XtxtUML executions should provide a simple way to populate the given model, i.e. to instantiate objects, associations and connectors. Note that this happens _inside_ the model, therefore there's no need to provide language elements neither for [API](https://github.com/ELTE-Soft/txtUML/blob/13e6e86a70868491505f3b41b795c34ae28b46ac/dev/plugins/hu.elte.txtuml.api.model/src/hu/elte/txtuml/api/model/API.java) calls nor for the new [model execution interface](https://github.com/ELTE-Soft/txtUML/blob/13e6e86a70868491505f3b41b795c34ae28b46ac/dev/plugins/hu.elte.txtuml.api.model.execution/src/hu/elte/txtuml/api/model/execution/ModelExecutor.java).

We have agreed on the following solution:
The syntax of executions doesn't need to be changed at all. Instead, only the translation of executions should be modified such that from each execution element a new Java class is generated with the same name and with two public static void functions. One of these functions should be called `init`, and it should contain the JtxtUML action code translated from the original execution body. The other function should be a conventional Java main function where a model executor should be created, initialized with the aforementioned `init` function and eventually launched with the _most typical_ configuration.

This way, executions could
- provide a simple and fast way to test models,
- be executed directly,
- be customized by creating a new Java class with a main function, where the user could define an individually configured model executor while still being able to use the generated `init` function as initializer, and perform [API](https://github.com/ELTE-Soft/txtUML/blob/13e6e86a70868491505f3b41b795c34ae28b46ac/dev/plugins/hu.elte.txtuml.api.model/src/hu/elte/txtuml/api/model/API.java) calls to communicate safely with the model from the outside world.

**Comment by kovacsgabor** [comment]
See #554. I think this upcoming feature will make it easier for you to create execution in X.

**Comment by djnemeth** [comment]
As #554 was closed by the recently merged #555, we could build upon the interface introduced there indeed.

**Comment by djnemeth** [comment]
The team have decided to postpone this.
