### ISSUE TITLE
Documentation of the ModelExecutor

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#444]
In the 'User Guide', please create a new subsection under 'Running and debugging models' about creating a Java main function and the usage of the ModelExecutor class. The documentation should give simple examples for typical use cases (eg. sending all signals in the init function and terminating after they are processed; waiting for initialization and waiting for user actions to send signals into the model; etc.) and refer the reader to the API documentation of the ModelExecutor class for further details.

**Comment by GregoBalu** [comment]
I believe this is done (see here: [clicky](http://txtuml.inf.elte.hu/wiki/doku.php?id=v051:userguide#running_and_debugging_models)).

**Comment by kovacsgabor** [comment]
No, it was incomplete but I finished it now.
