### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Aliamondo** [ELTE-Soft/txtUML#445]
- The page [[http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:layout]](http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:layout) contains **Simple layout constraints for nodes**, which specify relative layouts. Among those layouts are `@East(val = A.class, from = B.class)` and `@West(val = A.class, from = B.class)`, which both have the exact same description:
`The diagram can be cut vertically such that A is in the right half and B is in the left half.` That makes sense for East, but not for West.
- On the other page [[http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:language]](http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:language) there is a typo in **Ports and connectors**, namely "B**a**havior ports"

**Comment by djnemeth** [comment]
Fixed. Thanks for the report!
