### ISSUE TITLE
Relationship between Diagram description and model

### ISSUE THREAD

**Issue by dobreffandras** [ELTE-Soft/txtUML#465]
During the improvements of the diagram visualization UI we faced an issue which caused not so user-friendly solutions many times. [1](https://github.com/ELTE-Soft/txtUML/pull/464#issuecomment-264698970), [2](https://github.com/ELTE-Soft/txtUML/issues/438#issuecomment-251801602)

There is no way right now to determine the model which a diagram description belongs to.

Since there are more examples where this feature could raise the user experience and eliminate confusion, I suggest creating the capability of a diagram description determining its model.

**Comment by dobreffandras** [comment]
@nagyandras95 If I'm not mistaken the same problem occurs regarding the configurations.

**Comment by dobreffandras** [comment]
The first solution that came to my mind has been previously introduced by @GregoBalu:

A diagram description can enumerate the ModelClasses that are to be placed on the diagram. If there are ModelClasses from different models the diagram description becomes invalid. Because of this constraint the model can be determined by the first ModelClass of the enumeration.

**Comment by nagyandras95** [comment]
Yes, this issue refers to the deployment configuration too.

**Comment by dobreffandras** [comment]
On the meeting the team agreed on the following:

In some cases the user may want to create a diagram with members deriving from several models. These cases can be tricky and right now the tool-chain (e.g. layout-export) does not support diagrams referring to multiple models. 

The short term solution will be as suggested above: The model has to be determined from the diagram description. With this feature selecting the project and model on the visualization wizard (and similarly on the cpp-gen wizard) is not needed anymore  and intended to be removed.

Diagrams with multiple models has to be discussed later in the future.
