### ISSUE TITLE
Object equality and inequality checks

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#47]
The current support for object equality and inequality checks (the use of == and != operators on objects) in exported models was quickly made to avoid a ```NullPointerException``` during exportation. Please, review this and look for a better solution if possible.

**Comment by kovacsgabor** [comment]
@nboldi, were you aware of this issue when you started working on the model exportation? Is it fixed?

**Comment by nboldi** [comment]
I did not modified the existing code dealing with equality compare.

**Comment by nboldi** [comment]
But first, I would like to merge the current solution and than refactor it in a new branch because I'm sure that there are a lot of hidden bugs in it.

**Comment by kovacsgabor** [comment]
It is just OK. This is minor issue, and I only wanted to make sure that it is not forgotten.

**Comment by nboldi** [comment]
Currently `==` and `!=` check on objects that are not integers or booleans are translated to operation calls to `ObjectOperations.eq`. Should we generate `TestIdentityAction` instead?

**Comment by kovacsgabor** [comment]
I think we should. The less stdlib operations we implement and use, the better.

**Comment by devaigergely81** [comment]
If the `TestIdentityAction` is comparing the equality of the references to object instances, then definitely yes.

**Comment by nboldi** [comment]
According to javadoc:
> A test identity action is an action that tests if two values are identical objects.
