### ISSUE TITLE
Diagram Generation Documentation (Errors)

### ISSUE THREAD

**Issue by Aliamondo** [ELTE-Soft/txtUML#481]
When the user creates the diagram class, it has to be in a package other than the model package. This, however, isn't mentioned on the [documentation page](http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:layout) of txtUML.
Not that it is a big problem, but the error messages in this case aren't that helpful in figuring out the problem with the diagram. I personally saw several new users of txtUML struggle with this problem already.

**Comment by djnemeth** [comment]
Thank you for reporting this issue. We will improve the documentation in this regard as part of the upcoming release.

**Comment by djnemeth** [comment]
Fixed, see the last paragraph of the [General structure](http://txtuml.inf.elte.hu/wiki/doku.php?id=v060:layout#general_structure) section in the Diagram Language Guide.
