### ISSUE TITLE
Error with some Import

### ISSUE THREAD

**Issue by DianaSuasnavas** [ELTE-Soft/txtUML#486]
When I cloned the repository, I found some errors, regarding with the folder example(hu.elte.txtuml.export.uml2.tests.models) in this project in the package behavport_connect, there are two classes (A.java and B.java) these classes cointain an error with unnecessary import (import hu.elte.txtuml.api.model.Port;) I looked into the project api model and the Port class doesn't exist

**Comment by djnemeth** [comment]
Thank you for reporting this issue. In general, models located in the *examples/tests* folder are meant only for (internal) testing purposes, therefore their consistency with the API is not guaranteed. For basic usage I recommend studying models from the *examples/demo* folder. By the way, the `Port` class is now defined inside `hu.elte.txtuml.api.model.ModelClass`.

@nagyandras95, as I can see, the aforementioned test project is still referenced in `hu.elte.txtuml.export.uml2.tests`. Do the reported errors affect the related unit tests in any regard?

**Comment by djnemeth** [comment]
Apparently, only the mentioned imports of `Port` could cause problems, as the remaining errors are issued by the JtxtUML validator, and as such, they don't really affect the underlying JDT AST, which really matters regarding the UML exporter. The reason why these import errors don't break the related unit tests is that references to `Port` still can be resolved using the import for `ModelClass`.

However, we should not forget to update the ones used by unit tests from the models located in _examples/tests_.
