### ISSUE TITLE
Problems in the Javadoc of the JtxtUML API

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#488]
During generating a Javadoc from the JtxtUML API and checking the result afterwards, I have discovered the following small problems:

- [x] In documentation comments of shorthand operations defined in ModelExecutor (`launch()`, `launch(Runnable)`, `run()`, `run(Runnable)`, `start(Runnable)`), the dots used for separating segments of the corresponding method chains are treated as sentence endings. As a result, in the generated method summary only the first segment of the chains is shown, which is really misleading. I believe this could be fixed by replacing these dots with their HTML entity number (`&#x2e;`).
- [x] `\api\model\execution\ModelExecutor.java:119: error: reference not found`
`"caused by them have been processed and all {@link TerminatePredicate}s"`
- [x] `\api\model\execution\ModelExecutor.java:134: error: reference not found`
`"{@link TerminationPredicate}s either)."`
- [x] `\api\model\execution\ModelExecutor.java:400: error: reference not found`
`"See {@link #setExecutorLog}."`
- [x] `\api\stdlib\timers\Timer.java:16: error: reference not found`
`"See the documentation of {@link hu.elte.txtuml.api.Model} for an overview on"`
- [ ] `\api\model\Runtime.java:111: warning - Tag @link:` 
`can't find connect(Class, Port, Class, Port) in hu.elte.txtuml.api.model.Action`
- [ ] `\api\model\Runtime.java:117: warning - Tag @link:`
`can't find connect(Port, Class, Port) in hu.elte.txtuml.api.model.Action`
- [ ] `\api\model\ModelClass.java:276: warning - Tag @see:`
`can't find connect(Port, Class, Port) in hu.elte.txtuml.api.model.Action`
- [ ] `\api\model\ModelClass.java:276: warning - Tag @see:`
`can't find connect(Class, Port, Class, Port) in hu.elte.txtuml.api.model.Action`

**Comment by kovacsgabor** [comment]
I solved the first 5 problems in https://github.com/ELTE-Soft/txtUML/commit/89cc1825d23a455b7f9a63a2461f6a0df2624d0b. For the last four, I couldn't find any solution, but we agreed with @djnemeth that they are not so important (the references appear in the generated javadoc, the only problem is that they will not be not links).
