### ISSUE TITLE
Improve condition evaluation in sequence diagrams

### ISSUE THREAD

**Issue by kmozsi** [ELTE-Soft/txtUML#535]
The condition evaluation of loops and selections is not fully implemented yet, and in its current state it does not work correctly.

**Comment by djnemeth** [comment]
@kmozsi, could you provide some details about the bugs you've found?

**Comment by kovacsgabor** [comment]
As simple Java if statements and loop statements are used, the sequence execution simply takes the path which is chosen by Java when the code is executed. Also, it is not solved how relevant information is taken out from the model in the sequence diagram description.

About the plantUML part, I have no information.

**Comment by djnemeth** [comment]
@kmozsi, is this still unresolved?

**Comment by kmozsi** [comment]
In #555 a new sequence diagram execution API has been introduced. Since then conditions are evaluated in parallel with model execution (using appropriate synchronization along message sendings) instead of evaluating before model execution, thus I think this issue has been resolved already.

**Comment by djnemeth** [comment]
I agree.
