### ISSUE TITLE
Changing Action.create?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#54]
Action.create might be enhanced with the use of lambda expressions.

Current syntax (with an `int` and a `boolean` parameter):

``` java
A a = Action.create(A.class, 2, true);
```

New syntax would be:

``` java
A a = Action.create(A::new, 2, true);
```

Pros:
- The creation of the new object would need no reflection and therefore it would be much faster.
- The number and type of the constructor parameters could be checked at compile time.

Cons:
- This change has to be applied to every level of our implementation.

**Comment by nboldi** [comment]
The referenced constructor is a two-parameter constructor? It would require to write a separate `create` method for every number of parameters possible (since the corresponding producer must be expected as the first parameter).

**Comment by kovacsgabor** [comment]
That it is true but it is not as bad as it sounds like.

By creating a default ```create``` method which would accept a Supplier lambda expression (one which creates a value without any parameters), all the other ```create``` methods could call this default one.

This default ```create``` method could look like:
```java
public static <T extends ModelClass> T create(Supplier<T> constructor) {
   //...
}
```
And then (for example) the two-parameter ```create``` could be:
```java
public static <T extends ModelClass, A1, A2> T create(
                              Constructor2<T, A1, A2> constructor, A1 arg1, A2 arg2) {
   create(() -> constructor.create(arg1, arg2));
}
```
Where ```Constructor2``` would represent a two-parameter constructor, being defined like:
```java
public interface Constructor2<T extends ModelClass, A1, A2> {
    T create(A1 arg1, A2 arg2);
}
```
We could generate (or manually write, as this is not so big work) different ```create``` methods and ```ConstructorN``` interfaces for constructors with, let us say, 0 to 10 parameters. I do not think that it is a common case to use constructors with more than 10 parameters. But if the user wish to use one, he or she still can:
```java
A a = Action.create(() -> new A(....));
```
It is not as nice as the other syntax, but I think it is acceptable as a fallback solution for constructors with more than 10 parameters.

**Comment by kovacsgabor** [comment]
MDD team: OK.

**Comment by kovacsgabor** [comment]
@ELTE-Soft/all, please comment if you disapprove.

**Comment by nboldi** [comment]
@kovacsgabor, what is the status of this issue?

**Comment by kovacsgabor** [comment]
It is not done yet.

**Comment by kovacsgabor** [comment]
I remove this proposal. I do not think now that this feature is worth the effort.
