### ISSUE TITLE
Sequence diagram validation

### ISSUE THREAD

**Issue by kmozsi** [ELTE-Soft/txtUML#559]
Sequence diagrams should be validated during their description (for example blocks without `Sequence.send` calls should not be allowed; lifeline positions must be also validated). 
Please check the already existing solutions for validation.

**Comment by djnemeth** [comment]
See the [JtxtUML validator](https://github.com/ELTE-Soft/txtUML/tree/a4c1257726bd44068525394916193a300bdf014d/dev/plugins/hu.elte.txtuml.validation/src/hu/elte/txtuml/validation).
