### ISSUE TITLE
Split models into more files?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#56]
It is inevitable to let JtxtUML models to be split into more files. So the only question that remains is **how** to do it.

For the validation and the UML2 export it is a necessity to maintain some connection between the files of a model as we need to decide which files are part of it and which are not. My proposal is to keep all the files of a model in a single Java package and its subpackages. It would also be a good idea to have a main class representing the model in the top package. The subpackages could represent packages of the model.

**Comment by nboldi** [comment]
I think a single source dir for all files of the model would be more conventional.

**Comment by devaigergely81** [comment]
Packaging has the advantage that Java packages could be turned into UML packages. In fact, the UML standard says that a "model" is a special top level "package". This proposal reflects this very well. Furthermore, nboldi's suggestion about a "source dir for the model" would also be fulfilled, since the directory of the top level package would contain all model sources, albeit not in a flat way, but in a directory hierarchy if sub-packages are used in the model.

**Comment by kovacsgabor** [comment]
MDD team: OK to first solution (model = Java package and its subpackages).

**Comment by kovacsgabor** [comment]
It was suggested by @devaigergely81 that instead of defining a main model class inside the top package of the model, a custom annotation could be applied to this package (by creating package-info.java).

**Comment by devaigergely81** [comment]
This is the top priority language API enhancement now. This should be done very soon, to have time for the change in XtxtUML as well already in November, if possible.

**Comment by kmate** [comment]
I made the modifications related to XtxtUML on the split-models branch. Can someone review them?

**Comment by kmate** [comment]
@kovacsgabor: I think `@Model` should have `@Target(ElementType.PACKAGE)`, to ensure it is only placed on Java packages.

**Comment by kovacsgabor** [comment]
Yes, its absence is only a mistake. Thanks.

**Comment by kmate** [comment]
Some additional info from the weekly meeting for xtxtuml:
- remove the top-level model construction, and move its contents out (classes, associations, signals)
- create a new construction `model "ModelName";`
  - it must be the only element in the file if present
  - it must be placed into a model-info.xtxtuml
  - the model name is optional
  - validate somehow that it is present only in the top-level package
