### ISSUE TITLE
Changing associations?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#57]
After splitting up the JtxtUML models into more files (see #56 ), it will become a problem that classes and their associations become different Java classes with the former having no connection to the latter.

It is a problem in one specific case:
```java
class A extends ModelClass {}
class B extends ModelClass {}

class A_B extends Assocation {
  class a extends Many<A> {}
  class b extends One<B> {}
}
```
In this case, when an instance of ```A``` is created, it must have an ```A_B``` association to a ```B``` instance because the ```b``` association end has a multiplicity of 1..1 (zero is not permitted). As it would be very hard to validate this by analyzing the model, we must check this at runtime. But if class ```A``` does not know about the existence of the association, it cannot raise an exception (or show a warning message, etc.) if the required linking is not done.

For this, I have the following proposal:
 * Associations would become interfaces. As nested classes can be defined inside interfaces as well, it gives us no restrictions. Just the keyword ```class``` needs to be replaced before the declaration. (And, of course, the class ```Association``` would become an interface as well.)
 * Both of (or *each of* if we ever introduce n-ary associations in JtxtUML) the classes at the ends of the association (so ```A``` and ```B```) must implement this interface (the one that represents the association). As this is an empty interface with no abstract methods, this only affects the header of the classes.

So the previous example would look like:

```java
class A extends ModelClass implements A_B {}
class B extends ModelClass implements A_B {}

interface A_B extends Assocation {
  class a extends Many<A> {}
  class b extends One<B> {}
}
```

Pros:
 * This way, a class would know about all of its associations and could perform the required multiplicity checks (with reflection).
 * The user could also see all the associations at the file of a class.
 * It works fine with generalization.
 * Calling ```assoc``` could become simpler, as the association ends would be in scope without any specific imports:
```java
class A extends ModelClass implements A_B {
  void op() {
    B b = assoc(b.class).selectAny();
    // Instead of assoc(A_B.b.class)
  }
}
```

Cons:
 * More code for the user.
 * Must be checked with validation.
 * This change has to be applied to every level of our implementation.

**Comment by nboldi** [comment]
It seems a good idea to me. It is important to simplify scoping, because there will be many issues when models will be split into multiple files.

**Comment by devaigergely81** [comment]
Some issues:
* Users will complain about this: When they create an association, two validation errors will appear about the missing interface implementations. The classes may be far away, or even in other files. We could help the users by adding a quick fix for this validation error, which automatically inserts the necessary import declaration and provide keyboard shortcut.
* What about XtxtUML? If we keep the syntax there, then transforming the X syntax to J syntax requires the analysis of the full model just to find all associations mentioning the class currently transformed. We have to look into how this affects the Xtext+Xbase inference and compilation process.
* We have to decide how to support UML interfaces in txtUML. (Necessary for communication over ports.) If we end up using Java interfaces for that purpose, it will be confusing for the users that some interfaces are implemented because they are associations, others are implemented because they are UML interfaces.

**Comment by devaigergely81** [comment]
Just an idea: What if we extend the static validation process such that we generate "runtime validation classes" - Java files that contain information needed by runtime validation. In the example above we could generate classes "runtime.A" and "runtime.B" pointing to the association A_B. The runtime would try to find these runtime classes, and in case of success, use them to validate the multiplicity rules of the association.
Unfortunately this would not be available outside Eclipse, leading to less runtime validations there. Or provided as a separate, optional step before running the model.

What other runtime validation problems could we solve this way?

**Comment by devaigergely81** [comment]
Just an idea: What if we extend the static validation process such that we generate "runtime validation classes" - Java files that contain information needed by runtime validation. In the example above we could generate classes "runtime.A" and "runtime.B" pointing to the association A_B. The runtime would try to find these runtime classes, and in case of success, use them to validate the multiplicity rules of the association.
Unfortunately this would not be available outside Eclipse, leading to less runtime validations there. Or provided as a separate, optional step before running the model.

What other runtime validation problems could we solve this way?

**Comment by kovacsgabor** [comment]
No other runtime validation problem has come up. However, it is possible that some runtime validations could become easier (faster) this way. I will think about it.

Another note: Boldi said today that it is possible to use JDT without Eclipse. So the validation (and therefore these generated classes) wouldn't be necessarily missing with lack of Eclipse.

**Comment by kmate** [comment]
Some information on how to use JDT in a standalone application: http://www.programcreek.com/2011/01/a-complete-standalone-example-of-astparser/

**Comment by kovacsgabor** [comment]
We should see if some external features (like AspectJ) help us solve this problem without changing the syntax.

**Comment by kovacsgabor** [comment]
The original proposal about changing association syntax is unsupported, so I close this issue.
