### ISSUE TITLE
Sequence diagram examples

### ISSUE THREAD

**Issue by kmozsi** [ELTE-Soft/txtUML#571]
Some sequence diagram examples for demo projects should be provided.

**Comment by djnemeth** [comment]
@kmozsi, what is the status of this issue?

**Comment by kmozsi** [comment]
Sequence diagrams have been added to _machine_, _monitoring_, _producer-consumer_ and _train_ demos. After implementing #590 in the future, our other demo models will become testable, so examples should be provided for them too.

**Comment by djnemeth** [comment]
Then I believe it is more of an ongoing task (as new demo examples will likely be added in the future) rather than a specific issue, therefore I close this for now.
