### ISSUE TITLE
Changing transitions?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#58]
Current syntax:

``` java
@From(Init.class) @To(Active.class)
class Initialize extends Transition {}

@From(Active.class) @To(Active.class) @Trigger(DoTasks.class)
class DoActivity extends Transition {}
```

Modified syntax: (1)

``` java
class Initialize extends UnlabeledTransition<Init, Active> {}

class DoActivity extends Transition<Active, Active, DoTasks> {}
```

Or: (2)

``` java
class Initialize extends Transition<Init, Active> {}

@Trigger(DoTasks.class)                
class DoActivity extends Transition<Active, Active> {}
```

Pros:
- Less coding for the user.
- Parameters are guaranteed to be given.
- Solution (1) can give type safety when asking for the signal instance in the `effect` or the `guard` method, instead of the `getSignal` method which currently uses unchecked cast to any signal type the user wishes to get.

Cons:
- Not so self-explaining, therefore harder to read (at least as a beginner to JtxtUML).
- In case of solution (1), labeled and unlabeled transitions need differentiation, either by the way showed above or by introducing a special `NoSignal` (or something like that) signal type, which by given as a type parameter shows that the transition is unlabeled.

I am not sure which syntax gives better execution speed because all of them need reflection but they need to ask for different information.

**Comment by devaigergely81** [comment]
I like solution (1), except the name `UnlabeledTransition`. If the trigger is only missing in case of an initial transition, we could use `Initialization` instead:
~~~~
class InitState extends Initial {}
class FirstState extends State {}
class InitTrans extends Initialization<InitState.class, FirstState.class> {}
~~~~
We could simplify this even more, if we omit the definition of the initial state and only declare an initial transition (and generate the initial pseudostate implicitly during model export):
~~~~
class FirstState extends State {}
class InitTrans extends Initialization<FirstState.class> {}
~~~~

**Comment by kovacsgabor** [comment]
We also use unlabeled transitions from choice pseudostates.

**Comment by devaigergely81** [comment]
For the transitions from choice nodes, we could have something like this:
~~~
class Case1 extends Case<ChoiceState.class, State1.class> {
   boolean condition() {
       // ...
   }
}
~~~

**Comment by kovacsgabor** [comment]
Another proposal:
```java
class T1 extends Transition<From, To> implements Triggerable<MyTrigger> {}
```

**Comment by kovacsgabor** [comment]
I withdraw this proposal.
