### ISSUE TITLE
Cannot install without Moka

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#6]
Use clean Eclipse Luna Java edition, try to install the txtUML update site generated from txtUML trunk as of 2015-10-14.
The install fails, because it cannot find Moka.
~~~~
Cannot complete the install because one or more required items could not be found.
  Software being installed: txtUML 0.1.1.201510140920 (hu.elte.txtuml.feature.feature.group 0.1.1.201510140920)
  Missing requirement: txtUML Diagnostic Extensions 0.1.0.201510140920 (hu.elte.txtuml.diagnostics 0.1.0.201510140920) requires 'bundle org.eclipse.papyrus.moka.ui 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: txtUML 0.1.1.201510140920 (hu.elte.txtuml.feature.feature.group 0.1.1.201510140920)
    To: hu.elte.txtuml.diagnostics [0.1.0.201510140920]
~~~~

**Comment by kovacsgabor** [comment]
Moka is needed because of txtUML visual debugging.

**Comment by devaigergely81** [comment]
Yes, I know. But isn't it possible to configure the dependencies so that Moka is also installed automatically?

**Comment by djnemeth** [comment]
We've found a [way](http://stackoverflow.com/a/8279204) to add update site references to the exported feature. I've tested the method on a clean Luna client, and it resolves the problem indeed, i.e. using a modified update site, the txtUML plugin can be installed automatically.

---

According to this solution, *after* the feature is exported, one has to modify the file `content.jar` – located in the root directory of the exported update site – by adding the required repository references to the packaged `content.xml`.

In our case, the following two entries have to be added to the `references` tag of the `repository` node:

```XML
<repository uri='http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/extra' url='http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/extra' type='0' options='1'/>
<repository uri='http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/extra' url='http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/extra' type='1' options='1'/>
```

As it appears to be undocumented, I specify the meaning of the used attributes:
- `uri`: the URI of the referenced repo
- `url`: the URL of the referenced repo
- `type`: whether the referenced repo is an artifact or metadata repo
- `options`: whether the referenced repo (as an update site) should be marked `Disabled` or `Enabled` in Eclipse

As I can see, currently there's no support for defining repository references *before* the export (e.g. in `feature.xml`). It's also important to note that if **any** of the specified update sites has already been added by the user to available sites as **disabled** site, this solution **will not work**. However, this only means that in this case, the user has to re-enable the required update sites, or install the missing dependencies manually.

See the attached [content.txt](https://github.com/ELTE-Soft/txtUML/files/20163/content.txt) for a full example. The added references can be found at lines 11-14, including the references for Xtext at lines 11-12.

**Comment by gerazo** [comment]
I've found the solution: https://github.com/ELTE-Soft/txtUML/pull/90

**Comment by devaigergely81** [comment]
`discovery` sites are disabled by Eclipse by default:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=230323#c3

These pages might help:
http://www.eclipse.org/forums/index.php/m/597390/
https://wiki.eclipse.org/FAQ_How_do_I_create_an_update_site_%28site.xml%29%3F

**Comment by djnemeth** [comment]
As far as I know, defining repository references using `associateSites.xml` is [deprecated](http://stackoverflow.com/a/9790251/5484434).

**Comment by kmate** [comment]
In the model executor we did not have this problem, as we had a target definition which contains all external dependencies. Then the build system produced an all-in-one update site, which contained all dependencies transitively. We did not use the Eclipse update site export functionality.

**Comment by gerazo** [comment]
Our specific problem can be solved by Tycho (it can put options=1). Moreover even this or Máté's approach will be solved by our release engineering in the coming weeks. So let's accept that 2 zeroes should be changed to ones by hand in the content.jar https://github.com/ELTE-Soft/txtUML/pull/93

**Comment by gerazo** [comment]
See https://github.com/ELTE-Soft/txtUML/pull/93
