### ISSUE TITLE
Show signal type in signal-to-deleted-object warning

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#60]
When running a JtxtUML model, if an object is deleted, and then it would receive a signal, the message ```"Warning: signal arrived to deleted model object TestModelClass:obj_1"``` is shown.

In this message, the type of the signal should be shown.

It was also proposed to display the data carried within the signal. However, as signals (optionally) carry data within them as fields of the representing Java class, I think it would be very slow and not very informative to list them with Java reflection.

**Comment by nboldi** [comment]
Maybe define toString to use reflection that can be overridden in the actual event type? This way by defining toString the author can convey the semantic meaning of the event, instead simply displaying the data.

Also if the reflection is only used in error messages, performance should not be a problem.
