### ISSUE TITLE
Improve sequence diagram validation

### ISSUE THREAD

**Issue by kmozsi** [ELTE-Soft/txtUML#608]
To make definition of _correct_ sequence diagram descriptions easier, two more validation rules could be added. An incomplete solution for both rules has been implemented earlier (see #579).

- Each fragment of `run` method should contain at least one `Sequence.send` or `Sequence.fromActor` call. Invoked (private) methods of `run` should also be checked. This rule has been reverted before, see https://github.com/ELTE-Soft/txtUML/pull/597#pullrequestreview-129403811. 
- Calling `Action` methods from `run` should not be allowed due to threading issues. Currently only direct `Action` calls are handled, see https://github.com/ELTE-Soft/txtUML/pull/579#discussion_r195929821.

**Comment by jtamas96** [comment]
A part of this issue was solved in #618. The unsolved parts were moved into #623, #624 and #621, so I am closing this issue.
