### ISSUE TITLE
Configure XtxtUML execution running as txtUML Application

### ISSUE THREAD

**Issue by berpeti** [ELTE-Soft/txtUML#619]
When trying to run an XtxtUML execution as txtUML Application, the wizard does not find the correct Main class and configuration for the running.

![kep](https://user-images.githubusercontent.com/30949137/53113826-bdcdb700-3542-11e9-9450-d2d5639c9857.png)

**Comment by djnemeth** [comment]
@fanni96, @bszalay33, @csagataj2, please confirm that you can reproduce this issue.

**Comment by csagataj2** [comment]
It is working for me.

**Comment by berpeti** [comment]
Sorry, my issue description was not accurate enough. This issue is about, that the wizard can't find automatically the correct Main class (when double clicking on the txtUML Application when choosing the `Run as` option on X-style executions). This function works with the J-style executions.
