### ISSUE TITLE
Multiple model executions at runtime

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#62]
By making the ```ModelExecutor``` class instantiatable, it could be possible to run more than one model execution at once (on different threads). This would also bring our implementation closer to a parallel execution. However, this would have some overhead as certain ```Action``` calls (which should remain static for the convenience of the user) would need to access the ```ModelExecutor``` instance which runs them. For this, the ```Thread.currentThread``` method could be used (to get the current ```ModelExecutorThread``` and through it the ```ModelExecutor``` instance) which is certainly slower than a static method call.

**Comment by nboldi** [comment]
The executor instance could be stored somewhere in the scope (model, class, etc...), and could be used to perform these actions. So instead of `Action.create(...)` we could use `executor.create(...)`.

**Comment by devaigergely81** [comment]
What is the motivation for running more than one model in parallel using threads? (If automated test execution performance is the goal, the test cases could run also in different processes avoiding any synchronization costs.)

**Comment by kovacsgabor** [comment]
What if the running program contains more models as its components?

It is also a bit confusing that currently the model execution is static and therefore when it is terminated, it cannot be restarted only if the necessary classes are loaded again with a different class loader. Or by running a new JVM.

Moreover, the majority of the problems which come up if we decide to implement this feature (like the problem of the static ```Action``` methods finding the actual ```ModelExecutor``` instance), will also come up if we ever want to introduce parallelism to the models themselves. So sooner or later, we have to face them.

**Comment by kmate** [comment]
It is simply a very strange magic that the model execution is effectiveliy started by a class loader through execution of a static initializer block. Furthermore, it makes the unit testing of the executor itself more painful. I think it is not a big cost for the users to insert a single line into their main programs to start the execution...

**Comment by nboldi** [comment]
I agree. It was a pain in the ass while writing tests for `ModelExecutorThread`.

**Comment by gerazo** [comment]
So as it turned out, maven surefire uses different ClassLoaders which make this kind of magic failing. Moreover, it seems that a general solution is not possible without breaching API limits and using heavy reflection... and will still be good for the current version of maven only. So I upvote this issue to be very important.

**Comment by devaigergely81** [comment]
Agree.

**Comment by gerazo** [comment]
api.tests were disabled in maven, see https://github.com/ELTE-Soft/txtUML/commit/6b896f0f59e00500a4a0521f13eb7d1d7bc2eff2
If you are ready with the fix, do not forget to remove the pom.xml changes to put the tests back alive.
