### ISSUE TITLE
Model execution initialization

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#63]
In case of a running JtxtUML model, sending signals to model objects from an outer source (from code running on a different thread than the actual model executor thread) is always safe, that is, it cannot break the execution.

Certain other operations (like creating and linking new objects) can also be performed safely, but only with strict restrictions (to maintain thread-safety) which are not so self-evident. However, in a well-designed model, these operations are only needed to initialize the model execution (to populate the model).

If these initializing operations could be done **before** the model execution starts, than the same rules would apply to them as at any point during the execution (from inside the model). It would be even safer (or at least, much clearer) if these operations could be done on the model executor thread.

My proposal is to implement a ```ModelExecutor.start``` static method (or non-static with #62 ) which would accept an instance of a ```Configuration``` (or ```Initialization```) interface and would run its only method at the beginning of a model execution. Of course, this instance could be created with a lambda expression to be short.

This way, we could have a simple rule: from outside the model, only sending signals to objects asynchronously (with ```Action.send```) is legal, all other actions are prohibited to ensure the safety of the execution.

**Comment by nboldi** [comment]
> Certain other operations (like creating and linking new objects) can also be performed safely, but only with strict restrictions (to maintain thread-safety) which are not so self-evident.

Are these documented somewhere?

In general I would not argue for breaking up the process into initialization and execution. It would be more benefitial if these restrictions could be reduced with careful synchronization.

**Comment by kovacsgabor** [comment]
> Are these documented somewhere?

See the JavaDoc of ```hu.elte.txtuml.api.model.Model```, look for the section "Communicating with the outside world". ```Model``` is the "main" class of the modeling API and all general information is written at this class (all other classes and interfaces of the modeling API has a reference to this class as the source of an overview on modeling in txtUML).

> In general I would not argue for breaking up the process into initialization and execution. It would be more benefitial if these restrictions could be reduced with careful synchronization.

The problem is, that when calling ```Action.link```, for example, the API has no information (unless explicitly checked) if it was called from the executor thread or from elsewhere. In the former case, it is always safe, in the latter, however, it needs non-trivial synchronizations to ensure safety.

Even greater problem comes when the user wants to call methods or access fields of model objects as we cannot synchronize in these cases. But if they can write action code outside the model, the question will come up: "Why am I restricted not to do this or that when writing the same action code as in the model?" The answer is simple but maybe not so obvious: This is not the same action code as inside the model.

**Comment by kovacsgabor** [comment]
It might be another solution to introduce a similar but different interface than ```Action``` to use from outside the model. It could make it more clear what is possible and what is not from outside the model.

**Comment by devaigergely81** [comment]
In general, communication with the model should be done via external classes, so it is a good idea to restrict other types of communication while the model is running.
Earlier we had discussions on how the generated C++ code should communicate with hand-written C++ code. That discussion also ended up with the proposal of an initial function. Very similar to this proposal. See the "txtUMLExternal" page in our internal wiki.
All in all, I support the proposal.

**Comment by kovacsgabor** [comment]
@ELTE-Soft/all, what do you think?

**Comment by kovacsgabor** [comment]
It seems supported, and is required to implement #62.
