### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [ELTE-Soft/txtUML#64]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by gerazo** [comment]
Should we go on with the EPL?

**Comment by gerazo** [comment]
EPL was added

**Comment by devaigergely81** [comment]
This project might become an Eclipse project in the future, in that case, EPL is the simplest choice. On the other hand, some code was already copied by nboldi from the Model Executor project that has been released under EPL already.
