### ISSUE TITLE
Runtime javadoc are not accessible

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#69]
With the new library containers in the projects, the sources of the executor are not automatically accessible as they were. Is it a problem?

**Comment by kovacsgabor** [comment]
Is the JavaDoc accessible? If yes, than I do not think that the sources are needed.

**Comment by nboldi** [comment]
JavaDoc is missing, so I will correct this.

**Comment by nboldi** [comment]
Should the plugin sources be distributed in separate jar files (more conventional, but without the source jars, the user will not have javadoc) or should they be distributed inside the same jars (unconventional, bigger jar files)?

**Comment by nboldi** [comment]
Decision: put the source of the runtime library into the jar files.

**Comment by nboldi** [comment]
Somehow standalone installation of the txtUML feature currently does not work for me. This could delay this branch.

**Comment by nboldi** [comment]
Implemented and ready to merge: #148
