### ISSUE TITLE
C++ code generator is not available on the Eclipse interface

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#7]
First, the code generator should be updated according to the new activity export, then make it available from the Eclipse interface.

**Comment by GregoBalu** [comment]
Meeting: This is (at least) can be assigned to two people, we should break it up.
Personally: We should dedicate a person to the UI related stuff like "create new project", "visualize editor", "running", "exporting", etc. This is becoming larger and larger.

**Comment by devaigergely81** [comment]
First, the export should be finalized. Ádám is working on that. Once finished, Robi and N. András will update the code generator and make it available from the menu.

**Comment by kovacsgabor** [comment]
Solved in #238.
