### ISSUE TITLE
External classes: attributes (fields) or associations?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#70]
We have external classes in JtxtUML models but we cannot keep references to them as both possible ways to do this are currently forbidden in JtxtUML:
 1. To connect them to model classes through associations. To be honest, it is not "forbidden", but rather "unsupported". When associations were implemented, we did not even think about this case.
 2. Creating attributes (fields) of model classes that could save references of ExternalClass types. This is forbidden by validation.

So the question is: Should external classes become classes of the model with "full rights", that is, they could be part of associations or should they look more like data types by keeping references to them in attributes (fields)?

If we prefer the first case, another problem will come up: multiplicities. What multiplicities could an association end have which is connected to an external class? For example, is it allowed to have a multiplicity of 1..1? Or 1..*? If yes, this leads to more runtime validations needed.

**Comment by devaigergely81** [comment]
I vote for associations to connect external and model classes. I would allow any multiplicities, even the creation of external class instances from the model, if its interface permits.

**Comment by kovacsgabor** [comment]
Using associations without any restrictions on multiplicities is the supported approach as far as it is achievable.

**Comment by kovacsgabor** [comment]
We decided to connect external classes to modeled classes via associations, so the question is answered. The implementation is part of #254, therefore this issue is solved.
