### ISSUE TITLE
External classes: Java classes or interfaces?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#71]
The question is, whether external classes of a JtxtUML model should be implemented as Java classes or interfaces extending or implementing the ```ExternalClass``` interface.

Currently, they are classes which do not have to be part of the model "physically", that is, they do not have to be nested classes of the main class of the model (the one that extends ```Model```).

I think it would be better if they became full parts of the model. So after #56, they would have their own files inside the package structure of the model.

However, in this case, it could make things more clear if they were interfaces as their implementation is not really part of the model. Instantiating them could still remain possible through static methods of these interfaces. For example:

```java
// inside the model
interface Ext extends ExternalClass {
  static Ext create() {
    return new ExtImpl();
  }
  void a();
  void b();
  // ...
}

// outside the model
class ExtImpl implements Ext {
  void a() { /* ... */ }
  void b() { /* ... */ }
  // ...
}
```

**Comment by kovacsgabor** [comment]
Note: if in #70 we decide to use associations to connect external classes to model classes and also allow multiplicities with a lower bound other than zero, it may affect this question as well. See the following example:
```java
interface Ext extends ExternalClass { /* ... */ }
class A extends ModelClass { /* ... */ }

class Ext_A extends Association {
  class ext extends Many<Ext> {}
  class a extends One<Ext> {}
}
```
When creating an instance of ```Ext```, it should be validated if it is connected to an instance of ```A``` through ```Ext_A```. However, if we have no control over the creation of this instance of ```Ext``` (no super class defined in the API the constructor of which could perform the required checks) than these runtime validations are impossible.

It looks like a solution to this if we instantiate external classes with a method like ```Action.create``` (```Action.createExternal```, for example), but as external classes might be instantiated outside the model, this restriction could not be validated.

**Comment by devaigergely81** [comment]
As far as I remember, earlier discussions on the "capsule API" version of txtUML, we concluded to use interfaces both for external datatypes and external classes. Therefore I vote for interfaces here as well.

**Comment by kovacsgabor** [comment]
Using interfaces is the supported approach as far as it is achievable.

**Comment by kovacsgabor** [comment]
The supported proposal about externals in #284 makes this issue invalid.
