### ISSUE TITLE
Standard library as one or more models?

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#72]
If in #71 we choose to make external classes parts of the model, it will become a problem that external classes (currently only timers) defined in the ```hu.elte.txtuml.api.stdlib``` project are not part of the user's model and therefore not allowed to be used there.

I suggest that we make these external classes part of a txtUML model (or more models in the future) which then could be imported to the user's model.

**Comment by kovacsgabor** [comment]
This naturally leads to #73.

**Comment by devaigergely81** [comment]
Agree.
