### ISSUE TITLE
Import other models

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#73]
I think txtUML models need the feature to import other txtUML models (or parts of other models).

In JtxtUML, this could look like:
```java
@Import(OtherModel.class)
class MyModel extends Model { /* ... */ }
```
And in XtxtUML:
```
model MyModel {
  import OtherModel;
}
```

**Comment by devaigergely81** [comment]
If models become packages, it would be more natural to use Java imports when a model imports another one. Is there any technical problem with that?

**Comment by kovacsgabor** [comment]
No obvious technical problem has come up. We should see if the model exportation raises any.

**Comment by kovacsgabor** [comment]
As models are now packages, explicitly referencing them could only be possible through strings. Also, this feature does not seem to be a necessity, it could only help the users to write explicit dependencies between models but that is not worth the inconvenience.
