### ISSUE TITLE
Model export without diagrams

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#85]
If the visualization wizard gets finished without selecting any diagram descriptions, a Papyrus model is created without any diagrams.
![visuwizard](https://cloud.githubusercontent.com/assets/7555116/10716035/cfa250c4-7b2a-11e5-927a-1d5c17bebbee.png)
This is all right, but surprising for the first time. We have to think about how to make this more user friendly.
I have some alternative suggestions:
* When the project and model names are filled, but no diagram descriptions are added, show a warning at the top of the wizard window (in red, if possible): "No diagrams will be generated using the current setup, because no diagram descriptions are added."
* Use a check box under the text fields of the project and model: "Papyrus model with diagrams".
It should be checked by default. If checked, the diagram related controls are visible and validation ensures that at least one diagram description is added. If unchecked, these controls disappear.

**Comment by dobreffandras** [comment]
Considering that visualizing a model with no diagrams is a very rare use case, I mean I don't think anyone ever want to use the visualization feature that way, I wouldn't create a checkbox for that as it would be a handy feature; I'd stay by your first suggestion. Displaying a warning is the right way in my opinion. 
There are two ways we can do it: 
* As you suggested we could write a warning in the top of the wizard window. I don't know if it's possible to format these messages, but I think a warning can be well seen.
![wizardwithwarning](https://cloud.githubusercontent.com/assets/14291673/10717267/70a37de6-7b52-11e5-85ff-4674bd259aaf.png)
* Another way is to display a warning (yes/no) dialog with the message. When the user clicks yes the model will be generated with no diagram, when he clicks no, he will go back to the wizard.
![warninigdialog](https://cloud.githubusercontent.com/assets/14291673/10717269/7372ebe2-7b52-11e5-821c-31f5344586d9.png)
