### ISSUE TITLE
Release examples

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#88]
Some of the examples currently in the repo will be provided as sample models of release 0.2.0. To prepare this, the examples need to be fixed and put in a uniform shape:
* The validation error of the garage example cannot be fixed, because of #70, and will not be part of the release.
* The validation error of the printer example should be fixed. The queue there could be removed and the implicit message queues could be used instead.
* All examples to be released should have the following shape:
  * Has its own package, with meaningful name, containing the following 3 files.
    * XtxtUML model with execution description (.txtuml)
    * JtxtUML model and main function (.java)
    * Class diagram definition (separate .java file)
  * The naming conventions across all example projects should be the same.
  * The `XtxtUML + execution` and `JtxtUML + main` pairs should be isomorphic.
* Run/debug and diagram generation should be tested for all examples to be released.

**Comment by kovacsgabor** [comment]
Fixed in #107.
