### ISSUE TITLE
Oblique association lines

### ISSUE THREAD

**Issue by devaigergely81** [ELTE-Soft/txtUML#97]
Generated from the `hu.elte.txtuml.examples.train` example:
![diagramerror](https://cloud.githubusercontent.com/assets/7555116/10825202/39242a72-7e64-11e5-82b3-f59c320d1933.png)

**Comment by dobreffandras** [comment]
Problem and solution is explained in: #76

**Comment by kovacsgabor** [comment]
With the associated branch merged into master, is this issue fixed?
